### ISSUE TITLE
Pin Icon Tooltip

### ISSUE THREAD

**Issue by ToppDev** [thedmd/imgui-node-editor#100]
Hello,

I currently try to get a Tooltip working on the Node pins in your blueprints-example.

It works, but somehow the header of the tooltip bugs, but only if the node content is wider than the header.
Guess a gif says more than 1000 words.

![Peek 2021-01-06 13-02](https://user-images.githubusercontent.com/17766093/103767416-dd7c0480-5020-11eb-93f4-5121b69fb1a6.gif)

I did the following
```
for (auto& input : node.Inputs)
{
    auto alpha = ImGui::GetStyle().Alpha;
    if (newLinkPin && !CanCreateLink(newLinkPin, &input) && &input != newLinkPin)
        alpha = alpha * (48.0f / 255.0f);

    builder.Input(input.ID);
    ImGui::PushStyleVar(ImGuiStyleVar_Alpha, alpha);
    DrawPinIcon(input, IsPinLinked(input.ID), (int)(alpha * 255));
    // ---------------------- New Code start ------------------------------------
    if (ImGui::IsItemHovered())
    {
        ed::Suspend(); // If not done here, the Tooltip spawns somewhat far away from the mouse
        ImGui::SetTooltip("Some Tooltip");
        ed::Resume();
    }
    // ---------------------- New Code end -------------------------------------
    ImGui::Spring(0);
    ImGui::TextUnformatted(input.Name.c_str());
    ImGui::Spring(0);

    ImGui::PopStyleVar();
    builder.EndInput();
}
```

The problem I think lies in the `ed::Suspend()` and `ed::Resume();`. Because the same behavior occurs when the `ImGui::SetTooltip` line is commented out. So my guess is, that I should not call these while constructing a node. However then the Tooltip is not attached to the mouse but far away.

Could you push me somehow in the right direction to fix this?

**Comment by thedmd** [comment]
`ImGui::SetTooltip()` pushes some new geometry when it is called and this geometry contribute to the layout of the node. To prevent this from happening, instead of showing tooltip now you can remember for what pin you want to show it and call `ImGui::SetTooltip("Some Tooltip")` outside of the loop. Can you try that?

**Comment by ToppDev** [comment]
yes, that worked perfectly.

Could have thought of that myself, but I somehow thought the SetTooltip has to be directly under the item it should be shown for. However it just sticks to the mouse.

Thank you very much.
