### ISSUE TITLE
Rename "ImDrawList::AddBezierCurve()"  to  "ImDrawList::AddBezierCubic()"

### ISSUE THREAD

**Issue by Green-Sky** [thedmd/imgui-node-editor#103]
... since it has been renamed with ImGui v1.80.

Please test with `IMGUI_DISABLE_OBSOLETE_FUNCTIONS=1` from time to time.

Cheers.

**Comment by thedmd** [comment]
In a matter of fact, I will make it default. Thanks for pointing that out for me.
