### ISSUE TITLE
Imgui 1.82

### ISSUE THREAD

**Issue by SadE54** [thedmd/imgui-node-editor#107]
Hi , could it be possible to update your modified imgui version , at least on the dev branch please ? I trying to push on your IMGUI PR to get merged, it will be easier :)

**Comment by dayfox5317** [comment]
i have create a pull request ,you can clone it..(I am not sure if there will be any bugs)

**Comment by thedmd** [comment]
Internal copy of ImGui was updated to 1.84 (WIP). Please take look at 'develop' branch.

**Comment by thedmd** [comment]
@SadE54 `develop` branch has been updated to ImGui 1.84 (WIP).
