### ISSUE TITLE
Allow setting of Channel (z-axis) of Nodes

### ISSUE THREAD

**Issue by JaroslavHolecek** [thedmd/imgui-node-editor#109]
Hi,
it will be super, if you allow manual setting of Channel (z-axis) order of Nodes.
For example some switcher whether use your current implementation or manual setting of each Nodes.
Just add to Node variable for manual Channel and at the end allow sorting nodes based on this variable.
It will enlarge usability of library.
For example: I need draw Node with pins - and this node has as middle another Nodes - this is (i guess) impossible now - because if I select the main node it cover inside nodes...

**Comment by thedmd** [comment]
Hi!

You're correct there is no Z control for nodes in public API. Comment nodes (group nodes) are always under regular nodes, but this can be easily generalized to have custom Z value. Sounds like neat idea.

I will look into this.

**Comment by JaroslavHolecek** [comment]
Great! 
Can I ask you when you will have time to do it?
On your time depend, whether I wait for your update or somehow figure out my solution (my own simple node_editor)

**Comment by thedmd** [comment]
I will look into that this weekend. Will be raining, so there should be plenty of time for that. : )

**Comment by thedmd** [comment]
Nodes now can have Z position. This has highest priority when determining draw order.
```cpp
void SetNodeZPosition(NodeId nodeId, float z); // Sets node z position, nodes with higher value are drawn over nodes with lower value
float GetNodeZPosition(NodeId nodeId); // Returns node z position, defaults is 0.0f
```
