### ISSUE TITLE
Custom node creation

### ISSUE THREAD

**Issue by aabilityuk** [thedmd/imgui-node-editor#116]
Hi dear developers! First of all i want to thank you for a greate library! I need some help or tutorials of creation the custom nodes could you please direct me to the right place where to find an examples of how to change colors of PinType::Int and other pintypes? How to make a manual arrangement of pins inside the node? For example i have inputs and outputs:

s_Nodes.back().Inputs.emplace_back(GetNextId(), "5v", PinType::Int);
s_Nodes.back().Outputs.emplace_back(GetNextId(), "D2", PinType::Int);

and i want the inputs to be shown on the right side of the node instead of the left side

also i want to understand how to read and write state of the pins

Thank you !!!

**Comment by thedmd** [comment]
Hello. You're welcome.

> could you please direct me to the right place where to find an examples

At the moment blueprints example show most of the functionality of the library. One of the features is ability to create custom nodes. You can create them to look however you like as long as they have rectangular shape.

[UE-like blueprints nodes](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L926)
![image](https://user-images.githubusercontent.com/1197433/127601958-969421e2-1502-4db4-bd49-7578b40a7d01.png)
Here pints are layout in two columns, inputs on the left, output on the right.

[UE-like behavior tree nodes](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L1064)
![image](https://user-images.githubusercontent.com/1197433/127602075-37583ed9-b889-440f-93ed-d70c89d992df.png)
Input pins (one pin actually) is on the top, output pin is on the bottom.

[Houdini like nodes](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L1201)
![image](https://user-images.githubusercontent.com/1197433/127602185-b4bee3fc-1156-4b19-bf08-816aea82d3d9.png)
In Houdinig-style nodes input and output pins are positioned outside of the node boundary and are represented as circles.


Node Editor does care about rects for the most part. How things look like is up to the user of the library. You can draw custom pins in any shape as long as you tell editor about their bounding rect. In most basic application pins are simple ImGui widgets:
```cpp
ed::BeginPin(pinId);
ImGui::Text("I'm a pin");
ed::EndPin();
```

You can customize it using these functions:
```cpp
void PinRect(const ImVec2& a, const ImVec2& b);
void PinPivotRect(const ImVec2& a, const ImVec2& b);
void PinPivotSize(const ImVec2& size);
void PinPivotScale(const ImVec2& scale);
void PinPivotAlignment(const ImVec2& alignment);
```

`PinRect` - Explicitly sets pin bounding rect, if not called editor measure space occupied by pin widgets automatically
`PinPivotRect` - Here you can specify rectangle where pin pivot reside. By default it is zero sized rectangle inside pin rect.
If you create a link it will be draw between two closest point between two pins.
Yellow rect is a pin bounding rect, pin rectangle is a pivot rect.
![image](https://user-images.githubusercontent.com/1197433/127604258-9230fc49-81f0-48ce-b6c0-6bb880b48156.png)
You can customize placement of the pivot inside the rectangle using `PinPivotAlignment`. Input pins set it to [(0.0f, 0.5f)](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/utilities/builders.cpp#L250) (left middle), output pins set it to [(1.0f, 0.5f)](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/utilities/builders.cpp#L269) (right middle).
`PinPivotScale` - pivot scale influence calculated pivot size, not that useful in practice, I haven't found use for it yet

Here pivot rects match pin rect:
![image](https://user-images.githubusercontent.com/1197433/127604142-6112c2bc-4def-49c2-a554-02733c62ea13.png)

---

> how to change colors of PinType::Int and other pintypes

> also i want to understand how to read and write state of the pins

Node Editor is, well an editor. It does not implement blueprints for you. Example simply show some static data as a nodes.
In example pin types are defined [here](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L53). Colors are determined by the pin type [here](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L598).

There is a new example in works that actually is build on top of functional blueprints. Please see [feature/blueprint-next](https://github.com/thedmd/imgui-node-editor/tree/feature/blueprint-next/examples/blueprints2-example) branch. Be aware that, this is an experiment and it will change in the future.
![image](https://user-images.githubusercontent.com/1197433/127605685-468aef75-0022-474c-aa0c-7566dbd26a95.png)

---

> How to make a manual arrangement of pins inside the node

Simply change order they're drawn inside the node. Like any other UI made with ImGui.
Swap [inputs](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L986) with [outputs](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L1019). You will need to patch node builder too to make pinpivot appear in correct position. It was discussed earlier, near `PinPivotAlignment`.

**Comment by aabilityuk** [comment]
Thank you very much for a detailed response! I really appreciate it!!! Great and very usefull library. 

I didn't wait for response already, but after i recived the answer for sure i decided to stay making my project using your lib!!!

**Comment by thedmd** [comment]
Great you find it suitable for your needs. : )

If you do not find a solution in examples, ask question. I will answer them when I'm around.
