### ISSUE TITLE
Add node editor into custom application

### ISSUE THREAD

**Issue by PicosePablo** [thedmd/imgui-node-editor#12]
Hi!
Is there any form (that means: I cannot found it) to integrate the libs generated from your solution into my project?
I use GLFW3 & glad as a render. All in Windows.
I cannot add this to my project.
Nice work!!!!!!!!!

**Comment by thedmd** [comment]
Hello.

You can copy NodeEditor folder to your project and use CMake to link with it. Assuming that you're using CMake for project configuration.
Anyway, intention for NodeEditor is to be copied as source or CMake-based static library linked with your application.

**Comment by PicosePablo** [comment]
Ok just close it, I was doing something ridiculous with the entry xDDD
Sorry and NICE WORK!

**Comment by thedmd** [comment]
Ok : )

**Comment by Zerocjx** [comment]
Hi, how can i use the node-editor while I already have the latest imgui using for other GUI rendering.
Is there anyway to avoid the imgui conflict of node-editor using and mine ?

**Comment by thedmd** [comment]
I can bump editor to use ImGui 1.70. Node editor should then fit in.
