### ISSUE TITLE
How to Query for the current link we are trying to create

### ISSUE THREAD

**Issue by urosidoki** [thedmd/imgui-node-editor#123]
I would like to know if we are trying to create a link to see if I can do an extra validation on nodes to fade out those that are not compatible, and I haven't seen anything on the API to gather this data. Any idea?

**Comment by thedmd** [comment]
This is feature of the blueprint example, not node editor itself. You can see this in action there, as you start to create link, incompatible pings fade out.

[basic-interaction-example](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/basic-interaction-example/basic-interaction-example.cpp) is is about making new links:
https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/basic-interaction-example/basic-interaction-example.cpp#L131-L162

[blueprint-example](https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L1465) also display extra tooltip describing why connection isn't valid:
https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L1464-L1466

**Comment by urosidoki** [comment]
I meant before you connect the end of the link, I think I figure out how, you can use ed::QueryNewNode to get the pinId of the origin, so, that would allow me to inspect the type of the pin to apply an alpha to the nodes that are not compatible.

**Comment by thedmd** [comment]
You got it right.

Please note that user may drag link from the end to the start. So in this case endPinId will be valid, and startPinId will be not.
