### ISSUE TITLE
Use UUID as NodeId

### ISSUE THREAD

**Issue by urosidoki** [thedmd/imgui-node-editor#125]
Hi,

I was thinking about generating UUIDs for the objects I store in disk and use these UUID as NodeId, so I can ensure that the json stored will use the same UUID of the objects I have on disk.
Does anyone know if that is possible?

**Comment by thedmd** [comment]
Id's are made big enough to hold a pointer. If you want to use UUID's you can allocate them on the heap and use their addresses as Id's.

**Comment by urosidoki** [comment]
But nothing guarantees that the address will be same everytime you restart
the app. So the serialization code wont be able to position the nodes
properly right? Or am I missing something?
Cheers!

**Comment by thedmd** [comment]
No, there is no guarantee about pointer address. Configs `SaveNodeSettings` and `LoadNodeSettings` callbacks are made, so you can keep node state next to your object. This way you don't need to care about changing NodeId.

NodeId is meant to be run-time identifier.

**Comment by urosidoki** [comment]
Awesome, this is precisely what I needed.

Thanks!

**Comment by thedmd** [comment]
You're welcome :)
