### ISSUE TITLE
Crash on multi-threaded Flow animation (Blueprint example)

### ISSUE THREAD

**Issue by ToppDev** [thedmd/imgui-node-editor#129]
Hello,

I use your library in my project and sometimes experience crashes. I tried to track it down as much as I could, but hopefully you have a nice way how to fix this or a way for me to avoid it.

Thank you for creating this amazing library and hope you can help.

## Issue description

When having a lot of links and the Flow animation is invoked from a second thread, which is nor drawing the GUI itself, the program crashes.

## Steps to reproduce the issue

I made a simple example extending your blueprint example where the crash occurs. I was putting there a lot of nodes and links, however this crash occurs in my project with about 10 nodes and 48 links approximately.

1.  Checkout the `develop` branch and extend it with this commit https://github.com/ToppDev/imgui-node-editor/commit/43c710b620d04686b5196fe86448dc37de7a95cd or ofc directly clone the branch from my [fork](https://github.com/ToppDev/imgui-node-editor/tree/develop-flow-crash)
2. Compile the blueprint example and run it
3. Zoom out the flow, so all nodes are visible
4. Pressing the `Show Flow` Button works, but when pressing the `Show Flow Async` button, the application crashes

## Where does it crash

- Attaching the debugger I found out, that it crashes in `FlowAnimationController::Draw` function in **Line 3061**
https://github.com/thedmd/imgui-node-editor/blob/6c834d837fdd50f58e4ba6b436ab8c3eb0500743/imgui_node_editor.cpp#L3053-L3062

- The pointer `animation` is pointing to 0x00 or sometimes to 0x25 or something like this

## My guess why does it crash

- I think `m_Animations` was increasing in size while the for loop in L3060 was running (can happen because of second thread).
- It then reached a size causing the `std::vector` to reallocate its content. Therefore invalidating the ranged-based for loop.

## Possible fixes

- I replaced the ranged-based for loop with a normal for loop. That way it would request the element in the container every iteration instead of once at the start.
    ```C++
    for (size_t i = 0; i < m_Animations.size(); i++)
        m_Animations.at(i)->Draw(drawList);
    ```
- At least in my project it doesn't crash anymore with this fix. But it still crashes in the example I made for this issue :( . However the new crash my debugger refuses to track down.

### System information

- Operating System: Arch Linux 5.14.5-arch1-1
- Compiler: g++ (GCC) 11.1.0 / clang version 12.0.1

### Screenshots

![AsyncFlowCrash](https://user-images.githubusercontent.com/17766093/134774361-e7059ed9-de45-4fd9-9cd3-3176994b1ed8.png)
(green: works, red: crash)

**Comment by thedmd** [comment]
Hello ToppDev,

Thanks for detailed issue.

Node editor is not thread safe. This mean it isn't safe to call it's functions from different threads. Doing so will always lead to some kind of race condition. You were getting close to identifying the problem. This time this race manifested itself in range loop. One thread was busy drawing animations, second fired new animations changing `m_Animations` causing iterators to be invalidated and application crashed with access volition error.

The way to fix the issue is to delegate flow animation calls to editor thread.

In your example your were invoking `ed::Flow` from other thread:

```cpp
if (ImGui::Button("Show Flow Async"))
{
    std::thread _thd;
    _thd = std::thread([this]() {
        for (auto &link : m_Links)
        {
            ed::Flow(link.ID);
        }
    });
}
```

Instead you can delegate it to editor thread:

```cpp
std::vector<ed::LinkId> m_MyFlowAnimationQueue;
std::mutex              m_MyFlowAnimationQueueMutex;

if (ImGui::Button("Show Flow Async"))
{
    std::thread _thd;
    _thd = std::thread([this]() {
        const std::lock_guard<std::mutex> lock(m_MyFlowAnimationQueueMutex);
        m_MyFlowAnimationQueue.push_back(link.ID);
    });
}
```

On the editor thread you can process the queue:

```cpp
{
    const std::lock_guard<std::mutex> lock(m_MyFlowAnimationQueueMutex);
    for (auto &link : m_MyFlowAnimationQueue)
        ed::Flow(link.ID);
    m_MyFlowAnimationQueue.clear();
}
```

**Comment by ToppDev** [comment]
Hello thedmd,

thank you very much for your solution.
This solves the problem perfectly and it makes sense, that all GUI related functions should be called from the same thread while handling the thread safety on my side.
