### ISSUE TITLE
how do you ensure overlapping nodes work correctly?

### ISSUE THREAD

**Issue by wtholliday** [thedmd/imgui-node-editor#13]
Thanks for fixing the build! I got it working on Windows :)

You've done a nice job! I really like how the pins are highlighted during a connection drag. I'm the developer of [this app](http://audulus.com) which is one big node editor.

I noticed that in node editor examples [here](https://gist.github.com/ocornut/7e9b3ec566a333d725d4) (Dear IMGUI) and [here](https://github.com/vurtun/nuklear/issues/706) (nuklear), both have trouble rendering nodes that are overlapping.

It would seem that the typical immediate mode concept would have trouble with overlapping UI widgets, because the event order would be the same as the display order. That is, widgets that are drawn first process events first as well.

Does Dear IMGUI reverse the draw order? Or did you do something special in your implementation to handle overlapping nodes? It wasn't apparent to me from looking at the code.

thanks!

**Comment by thedmd** [comment]
You're welcome.

ImDrawList has ability to "split" rendering into channels. Channels are rendered in order, but active channel can be changed in any time. So I can first draw node to channel 2, background to channel 1, and selection to channel 0. They still be rendered in order 0, 1, 2. In editor I added an utility to resize list of channels and swap them which vanilla ImGui does not have.

Editor keep list of nodes sorted, selected/active nodes are always on top. Each node know own channel indices and I can swap them to match order of nodes.

In other words. Handling overlapping nodes is not an accident. : )

If you want to know more about channels inspect ImDrawList class, it is simple but powerful. Basically channel is an index buffer. Therefore reordering operation is cheap, no vertex data is touched in the process.

Whole magic is in `void ed::EditorContext::End()` function. Actually there is too much magic there but this not very relevant now. They are sorted there:
https://github.com/thedmd/imgui-node-editor/blob/60c8f6a479a8ef927b8b2d2ca862008a1b62a919/NodeEditor/Source/Editor.cpp#L1046-L1056

**Comment by wtholliday** [comment]
@thedmd Thanks for the explanation!
