### ISSUE TITLE
When create node   IM_ASSERT(size_arg.x != 0.0f && size_arg.y != 0.0f); is called

### ISSUE THREAD

**Issue by tianyu2** [thedmd/imgui-node-editor#134]
Hi am fairly new to node editors and trying to study how to use it when I try to create a node I get this assert anyone what might be the problem

**Comment by lance-loong** [comment]
https://github.com/thedmd/imgui-node-editor/pull/135
This is a repair commit.

**Comment by thedmd** [comment]
Fixed on `develop`.
