### ISSUE TITLE
Node won't render.

### ISSUE THREAD

**Issue by Stanlyhalo** [thedmd/imgui-node-editor#137]
Hi, I'm using DearImGui docking branch 1.83, and I have initialized the editor context, and set the current example, and am currently using the default example for the simple node. I have the window created, and the node created, but nothing appears in the window. Any help would be appreciated.

**Comment by Stanlyhalo** [comment]
I just realized, there's a docking branch, I'll try that.

**Comment by Stanlyhalo** [comment]
Well, docking branch didn't help.

**Comment by thedmd** [comment]
Can you try to reproduce issue using editor from `develop` branch?

**Comment by Stanlyhalo** [comment]
No I haven't, would you think it would fix it?

> Can you try to reproduce issue using editor from `develop` branch?

No I haven't, do you think it could work?

**Comment by thedmd** [comment]
There are fixes for ImGui docking on `develop` branch, so there is a fighting chance.

**Comment by Stanlyhalo** [comment]
@thedmd Sorry I didn't comment earlier, had something come up, yeah that didn't help sadly, still nothing shows up in my window.

**Comment by thedmd** [comment]
Is there anything drawn in the window?

**Comment by Stanlyhalo** [comment]
Nope, just blank, and yes, I copied+pasted the code from the example into where I would render stuff for that window.

**Comment by thedmd** [comment]
If there is absolutely nothing drawn it is very likely it has nothing to do with node editor itself.
With information I have I can advice you to debug and simplify your code to find source of failure.
