### ISSUE TITLE
 error C2660: 'ImGui::IsClippedEx': function does not take 3 arguments

### ISSUE THREAD

**Issue by Naios** [thedmd/imgui-node-editor#138]
6c834d837fdd50f58e4ba6b436ab8c3eb0500743 on https://github.com/ocornut/imgui/commit/7f38773b738e8d37b1a3c1d627205821300ef765

Hello @thedmd, it seems like 'ImGui::IsClippedEx' was changed recently and its arguments were reduced to two from three which causes

> error C2660: 'ImGui::IsClippedEx': function does not take 3 arguments

in imgui_canvas.cpp

```cpp
    if (ImGui::IsClippedEx(m_WidgetRect, id, false))
        return false;
```

**Comment by thedmd** [comment]
Fixed on `develop`. Thanks!
