### ISSUE TITLE
How to build? (faq)

### ISSUE THREAD

**Issue by ExtSolTech** [thedmd/imgui-node-editor#140]
Hy there,

Maybe this is a funny question, but how to build the examples?
I get errors with 'cmake --build build --config Release':

![image](https://user-images.githubusercontent.com/44647576/145367491-656d752f-4ba7-4d7d-a529-7e71dfb7a255.png)

**Comment by thedmd** [comment]
From https://github.com/thedmd/imgui-node-editor#examples.

Notice you need to generate project first, then you can build it:
```cmake
cmake -Hexamples -Bbuild -G "Visual Studio 15 2017 Win64"
cmake --build build --config Release
```

That being said, MinGW was not tested so you may hit some problems.

**Comment by ExtSolTech** [comment]
Really, thanks for the quick response, i'm still new to the world of cmake
