### ISSUE TITLE
How to make multyline node inputs and outputs?

### ISSUE THREAD

**Issue by aabilityuk** [thedmd/imgui-node-editor#146]
Hi, dear developers! Is it possible to make multycolumns node inputs and outputs? 

![изображение](https://user-images.githubusercontent.com/78211227/148345856-24b36093-b144-4a82-b4bd-c7dd4fb95b04.png)

Could you please give me a help with it? What should i start from?

I found some code in blueprints-example i think it relates to my question:

```
for (auto& input : node.Inputs)
            {

                auto alpha = ImGui::GetStyle().Alpha;
                if (newLinkPin && !CanCreateLink(newLinkPin, &input) && &input != newLinkPin)
                    alpha = alpha * (48.0f / 255.0f);
               
                    builder.Input(input.ID);
                    ImGui::PushStyleVar(ImGuiStyleVar_Alpha, alpha);
                    DrawPinIcon(input, IsPinLinked(input.ID), (int)(alpha * 255));
                    ImGui::Spring(0);
                    if (!input.Name.empty())
                    {
                        ImGui::TextUnformatted(input.Name.c_str());
                        ImGui::Spring(0);
                    }

                    if (input.Type == PinType::Bool)
                    {
                        ImGui::Button("Hello");
                        ImGui::Spring(0);
                    }
                    ImGui::PopStyleVar();
                    builder.EndInput();
            }
```
How should i change the layout with ImGui::Spring() or something else to be able to add three vertical columns with inputs and three vertical colunms with outputs to the node?

Also i found useful basic interactions example, and i was able to create what i mean:

```
void ImGuiEx_BeginColumn()
{
    ImGui::BeginGroup();
}

void ImGuiEx_NextColumn()
{
    ImGui::EndGroup();
    ImGui::SameLine();
    ImGui::BeginGroup();
}

void ImGuiEx_EndColumn()
{
    ImGui::EndGroup();
}

 ed::BeginNode(nodeB_Id);
        ImGui::Text("Node B");
        ImGuiEx_BeginColumn();
            ed::BeginPin(nodeB_InputPinId1, ed::PinKind::Input);
                ImGui::Text("-> In1");
            ed::EndPin();
            ed::BeginPin(nodeB_InputPinId2, ed::PinKind::Input);
                ImGui::Text("-> In2");
            ed::EndPin();
        ImGuiEx_NextColumn();
            ed::BeginPin(nodeB_InputPinId3, ed::PinKind::Input);
            ImGui::Text("-> In3");
            ed::EndPin();
            ed::BeginPin(nodeB_InputPinId4, ed::PinKind::Input);
            ImGui::Text("-> In4");
            ed::EndPin();
        ImGuiEx_NextColumn();
            ed::BeginPin(nodeB_OutputPinId, ed::PinKind::Output);
                ImGui::Text("Out ->");
            ed::EndPin();
        ImGuiEx_EndColumn();
    ed::EndNode();
```
But i don't know how to integrate it to blueprints example to be able to use the same behavior with "NodeType::Simple"

**Comment by thedmd** [comment]
Technically you can connect multiple links to same pin and achieve same result without making a pin board.

Node is drawn exactly like anything else in ImGui. You draw everything that need to be inside between `ed::BeginNode()/ed::EndNode()` calls.

**Comment by aabilityuk** [comment]
> Technically you can connect multiple links to same pin and achieve same result without making a pin board.

Thank you for reply! I know about that technically I can connect multiple links to the same pin., but visually I need what I mean)) could you please help with a small example how to make my task with a Simple node? ImGui is lack of documentation and I can’t find out how make it work... I understand that issues branch is not a candy shop and if you have a commercial branch I am ready to proceed with payment or donation

**Comment by thedmd** [comment]
You can place as many pins inside your node as you want. You can also make them look how you want them too. That one should be a given right now after looking at blueprints examples, where few types of visually distinct nodes were shown.

ImGui has every public function documented inside header file and have examples of usage in `imgui_demo.cpp`, not to mention ton of other details in project issue pages provided by users.

I'm afraid that I cannot write your code for you, and you need to seek this kind of help elsewhere.

I'm closing this as answered. Please post future help requests on your project page.

**Comment by aabilityuk** [comment]
@thedmd 
Could you advise any forums relates to node editor?

**Comment by thedmd** [comment]
I'm not aware of any forums related to the node editor.

My advice is to find any community that will help you get better at programming. That will enable you to use any library that is out there.
