### ISSUE TITLE
About the obsolete functions used in imgui-node-editor

### ISSUE THREAD

**Issue by Frank-Skywalker** [thedmd/imgui-node-editor#147]
I noticed that imgui-node-editor use some of the obsolete functions and definations of imgui header **imgui.h**  within macro: `#ifndef IMGUI_DISABLE_OBSOLETE_FUNCTIONS`.
I wonder if the extention will abandon these functions and when will the update be?
Best wishes.

**Comment by Frank-Skywalker** [comment]
Sorry, it seems that the develop branch has abandoned those obsolete functions?
Thanks for your efforts!

**Comment by thedmd** [comment]
Hi,

I usually drop use of obsolete functions on `develop` branch. Do you have trouble compiling with latest ImGui?

**Comment by Frank-Skywalker** [comment]
No, not now. Thanks very much!
