### ISSUE TITLE
Links rendering position incorrect.

### ISSUE THREAD

**Issue by Stanlyhalo** [thedmd/imgui-node-editor#148]
So I essentially just copied+pasted the basic-interaction-example (of course made it run in my engine), and the lines are in the wrong spot for the links/connections. How do I fix this? On top of this, how do I customize the nodes (as well as the background)?
![image](https://user-images.githubusercontent.com/36088749/150657931-1f2f7777-0962-4d91-98b4-8a5063ab5265.png)

**Comment by Stanlyhalo** [comment]
Okay, I'm slowly figuring out that the way to style is just to use the drawlist and stuff like ed:GetNodePosition and such. But how do I fix these rounded corners and fix the line positioning?
![image](https://user-images.githubusercontent.com/36088749/150661379-d32df0f1-8181-4d49-8b78-2b23a79bdb0b.png)

**Comment by thedmd** [comment]
You can change node rounding via `ed::GetStyle().NodeRounding = 0.0f`.

Link is drawn from the pivot point. By default this is center of the widget drawn between `BeginPin()/EndPin()` calls.
You can call `PinPivotAlignment(ImVec2(1.0f, 0.5f))` to move pivot to the middle of the right edge, for example. There are more function that allow you explicitly control pivot rectangle size/scale.

You can use this snipped to visualize how big pin rectangle is:
```cpp
// #debug - call after EndPin() to show pin rect
ImGui::GetWindowDrawList()->AddRect(
    ImGui::GetItemRectMin(), ImGui::GetItemRectMax(), IM_COL32(255, 0, 0, 255));
```

**Comment by Stanlyhalo** [comment]
Thanks! I'll be sure to do this, currently just dealing with another issue involving ImGui, but once that's out of the way, I'll be able to test this, so for now I'll close this issue unless I need clarification or more help on this topic.
