### ISSUE TITLE
Weird purple line on edges?

### ISSUE THREAD

**Issue by Stanlyhalo** [thedmd/imgui-node-editor#150]
I'm having a strange weird rendering issue, this has happened for a while now, but just ignored it. In certain zoom levels, these purple lines on the edges will either be rendered or not rendered, and with random thicknesses (although always thin).
![image](https://user-images.githubusercontent.com/36088749/150913407-d1e6ad80-62e9-4fd4-a124-2a58ef38cbd5.png)
Any known issue or cause?

Edit*: Also would like to add that sometimes clicking & dragging don't work.

**Comment by Stanlyhalo** [comment]
It appears I'm only able to move the node if it's currently in the view of where the window zoom and position was b4 (so in the picture, if I zoom out, and move the node way left, and zoom back into the exact same spot, it would be outside the window, so if I actually zoom to where the node is, and try to move it, it seems to think it's not in the window view or something)

**Comment by Stanlyhalo** [comment]
My second issue in this post appears to be the same as: https://github.com/thedmd/imgui-node-editor/issues/105
Still have not figured out the first issue, still looking into it.

**Comment by Stanlyhalo** [comment]
**Update**
I have just downloaded the `develop` branch of this repo, and it solved my node issue, but now I just have the purple line issue.

**Comment by thedmd** [comment]
There is a pink line around canvas. I didn't noticed it because it was covered by frame. I will look why it is there.
![image](https://user-images.githubusercontent.com/1197433/151316553-609c9b09-c005-4132-95b0-fe328c451d2b.png)

**Comment by thedmd** [comment]
Fix is pushed on develop.

If you want to get rid of the line, go to imgui_canvas.cpp:118 and comment out `m_DrawList->AddRect` line.
