### ISSUE TITLE
How to get position in graph from cursor pointer.

### ISSUE THREAD

**Issue by Stanlyhalo** [thedmd/imgui-node-editor#151]
This is a very simple question, answer may vary though xD Essentially, I have it so I can now create nodes on the fly and I get the position of where I opened the context menu via the typical `window->DC.CursorPos`, however, how would I turn this into a position on the graph? Or is there a way to just get an ImVec2 return value from getting where the cursor is at on the graph/canvas?

Edit*: Yes, I've tried the `ScreenToCanvas` method, didn't work, well, it just places it at the top left of the window.

**Comment by thedmd** [comment]
Can you try to call `ScreenToCanvas` between `ed::Begin()/ed::End()` or at least after first call to `ed::Begin()`?

This is why canvas is setup in `ed::Begin()`, before that it hold identity transformation. Does this help?

**Comment by Stanlyhalo** [comment]
Okay, well I will have to make a workaround because I have to put the context menu outside the `ed::Begin()`.

**Comment by Stanlyhalo** [comment]
Well I tried to call it between the `ed::Begin()/ed::End()` but it doesn't seem to work, still appears at the top left.

**Comment by Stanlyhalo** [comment]
Okay, I figured it out, it was both because I needed to call it after `ed::Begin()` and also imgui kept returning the top left as the mouse position which is weird.
