### ISSUE TITLE
Combo box drop down position

### ISSUE THREAD

**Issue by blockout22** [thedmd/imgui-node-editor#154]
I'm having some issues with using combo boxes inside a node, when I click on the drop down the menu doesn't appear in the right location, I also am unable to click the options in the dropdown.

what is the ideal work around for this?

I am using Java bindings https://github.com/SpaiR/imgui-java

![image](https://user-images.githubusercontent.com/4086993/156653943-dcc02b9a-252d-4323-9f2f-d808c0f62bea.png)

**Comment by crolando** [comment]
Hello, there is a work-around that is explained here:
https://github.com/thedmd/imgui-node-editor/issues/48

There is a code example in this example in the develop branch starting at line 221
https://github.com/thedmd/imgui-node-editor/blob/develop/examples/widgets-example/widgets-example.cpp

**Comment by thedmd** [comment]
At the moment there is no other way to handle combobox other than use workaround crolando is talking about (#48)
I tried every approach to fixup position without modifying ImGui itself.
I will continue looking for possible not-invasive solutions.
