### ISSUE TITLE
Imgui 1.86 WIP with docking support

### ISSUE THREAD

**Issue by Ubpa** [thedmd/imgui-node-editor#155]
Hi, I found that imgui-node-editor does not support with imgui 1.86 docking.
Could you please fix the bug?
![image](https://user-images.githubusercontent.com/15104079/156875114-61ece6e6-3a34-4dd1-9990-975b4faa68ae.png)

**Comment by thedmd** [comment]
I will check it out

**Comment by arabine** [comment]
Same thing here, I'm using your branch 1.89 WIP (18808), I cannot dock the window :'(

**Comment by thedmd** [comment]
Can you provide a repro?

So far I didn't manage to not make it work.

**Comment by arabine** [comment]
Ah!
I have added your simple example to my global frame drawing:

```cpp
void Blueprint::OnFrame()
{
    auto& io = ImGui::GetIO();

            ed::SetCurrentEditor(m_Editor);
            ed::Begin("My Editor");
            int uniqueId = 1;
            // Start drawing nodes.
            ed::BeginNode(uniqueId++);
                ImGui::Text("Node A");
                ed::BeginPin(uniqueId++, ed::PinKind::Input);
                    ImGui::Text("-> In");
                ed::EndPin();
                ImGui::SameLine();
                ed::BeginPin(uniqueId++, ed::PinKind::Output);
                    ImGui::Text("Out ->");
                ed::EndPin();
            ed::EndNode();
            ed::End();
            ed::SetCurrentEditor(nullptr);

    return;
```

All other windows are docked, when I drag this window I do not see any "blue anchor rectangle". Here the main loop (I'm using SDL2 as renderer):

```cpp
    int Update(SDL_Renderer *renderer, double deltaTime) override
    {
        draw_editor_layout();
        draw_memory_editor();
        m_blueprint.OnFrame();  // <<------- The Node editor is here
        draw_ost_device(renderer, deltaTime);
        code_editor_draw();

        m_console.Draw("Console", nullptr);

        return 0;
    }
```cpp

**Comment by arabine** [comment]
Hello do you need more information? I will try to push my project for you.

**Comment by thedmd** [comment]
`ed::Begin` does not create own window. Can you try to enclose code in `OnFrame()` in `ImGui::Begin()`/`ImGui::End()`?

**Comment by arabine** [comment]
Yes it works, thank you it was obvious now.

**Comment by ChivenZhang** [comment]
> 1.86

The newest version of imgui is 1.89, and there's bug when integrate node-editor. It occurs when zooming and scrolling.

**Comment by thedmd** [comment]
As a workaround please avoid running editor with zero size od when `ImGui::GetContentRegionAvail()` is an empty rect. This will be fixed in the future.

Also, please in the future open new issue instead of hijacking older ones.
