### ISSUE TITLE
Add topic tag "node-editor" to this repository.

### ISSUE THREAD

**Issue by simonwinkelbach** [thedmd/imgui-node-editor#157]
To help other people find this project, some topic tags should be added.
E.g. the topic "node-editor", see https://github.com/topics/node-editor
This is how to add topics in GitHub: 
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

Thanks for the great project.

**Comment by thedmd** [comment]
Thank you for suggestion, I did missed this feature. I added relevant topics to the project.
