### ISSUE TITLE
null-pointer exception in RendererDX11 on DPI change

### ISSUE THREAD

**Issue by connorjak** [thedmd/imgui-node-editor#162]
In my app which is derived from the Blueprints example (https://github.com/connorjak/Connectatron/tree/3547d2daa75070b9082aeedbc1d32b2838dc40e7), there is a null-pointer exception in `RendererDX11::RenderDrawData()` on mouse-release after dragging the window across a boundary between my 200%-scaling main display and 100%-scaling second display:

![image](https://user-images.githubusercontent.com/19719887/167034626-134ed2d4-143d-4ec8-8770-0f5530623b93.png)

![image](https://user-images.githubusercontent.com/19719887/167034646-3ad088dd-c6fe-4399-be03-7afd3966fd3a.png)

![image](https://user-images.githubusercontent.com/19719887/167034680-fe393bd3-3c35-49fe-9035-9c6dd448498d.png)

![image](https://user-images.githubusercontent.com/19719887/167034707-5e33365b-fef1-4a61-811b-059668bb12ae.png)

imgui-node-editor version: https://github.com/thedmd/imgui-node-editor/tree/6c834d837fdd50f58e4ba6b436ab8c3eb0500743

**Comment by thedmd** [comment]
Is example from `develop` branch is also crushing for you?

**Comment by connorjak** [comment]
I haven't tried since the commit I marked (6c834d837fdd50f58e4ba6b436ab8c3eb0500743)

**Comment by thedmd** [comment]
This is now fixed on `develop`.

You can cherry-pick 2968746, that will resolve crash.

If you use example harness, you may need 89312bb too.

Thanks for reporting.
