### ISSUE TITLE
How to intercept right mouse button in node editor region

### ISSUE THREAD

**Issue by Frank-Skywalker** [thedmd/imgui-node-editor#163]
Dear thedmd, I'm now using your node editor in engine tool development. And I found the right mouse button isn't Intercepted by node editor, thus caught by the engine IO. Is there any solution?
Best wishes.

**Comment by thedmd** [comment]
1) You can place node editor in borderless child window, which will capture all mouse events.
2) You can place ImGui::InvisibleButton() over whole node editor and it will catch all events, node editor didn't.
