### ISSUE TITLE
blueprints-example core dumps

### ISSUE THREAD

**Issue by rathken** [thedmd/imgui-node-editor#164]
Getting:  imgui-node-editor/build/bin$ ./blueprints-example 
blueprints-example: imgui-node-editor/external/imgui/imgui_widgets.cpp:705: bool ImGui::InvisibleButton(const char*, const ImVec2&): Assertion `size_arg.x != 0.0f && size_arg.y != 0.0f' failed.

Any hep to solve would be great. The other examples all run fine....

**Comment by gorilux** [comment]
Hi,
If you rename Data directory to lower case in the blueprints-example.cpp the example works perfectly
<
```
s_HeaderBackground = Application_LoadTexture("data/BlueprintBackground.png");
s_SaveIcon = Application_LoadTexture("data/ic_save_white_24dp.png");
s_RestoreIcon = Application_LoadTexture("data/ic_restore_white_24dp.png");
```

**Comment by thedmd** [comment]
Sorry for inconvenience. `develop` branch already had that fixed.
