### ISSUE TITLE
Issue with begin of node editor causing a leak

### ISSUE THREAD

**Issue by Erick9Thor** [thedmd/imgui-node-editor#165]
Hello guys!.

We are trying to implement state machine using your library but when we execute as the begin we always have the same leak. 448 bytes.
It's always the same and always appears whe we open the windows that contains the state machine.

Do you have any record of this happening?

Heare the code https://github.com/AkitaInteractive/Hachiko-Engine/blob/fix/state-machine-fixes-and-leaks/Source/src/ui/WindowStateMachine.cpp

Screenshot:

![image](https://user-images.githubusercontent.com/14850255/174877429-562f38d6-910e-4733-969e-6f3325c3f1cc.png)

**Comment by thedmd** [comment]
Fixed, editor should now behave and not leak memory.
