### ISSUE TITLE
I have suggestions after heard you are refactoring

### ISSUE THREAD

**Issue by tim3385** [thedmd/imgui-node-editor#17]
Hi, first of all, nice job, and thank you for your hard work.
I personally hope that you can make your library lighter, concise and easier for others to integrate into their own projects and secondary develop. You know, there are now libraries of single-header files, and their authors are very fond of lightweight.

**Comment by thedmd** [comment]
Thank you, I hope you find it useful.

I'm aware of single header libraries. Reducing number of dependencies is something I have in mind.
Second version of editor is baking in the oven, where the goal is to cleanup and separate prototyped functionality. I have in mind ease of integration so I will do some extra work to make it foldable into single header form.

Fell free to throw any other suggestions.
