### ISSUE TITLE
Object containers in the EditorContext are not properly cleaned up

### ISSUE THREAD

**Issue by shamilatesoglu** [thedmd/imgui-node-editor#173]
The object containers `m_Nodes`, `m_Pins`, `m_Links` inside `EditorContext` are not properly cleaned after a node or link is deleted. As long as the same `EditorContext` is used, these containers continue to inflate. So when a node is deleted, if a same ID is used to create another node, the `FindNode` function returns the previous node object with the settings of the previous node. In groups, for example, this problem causes it to have the previous group's size when a new group with the same ID is created (after the first one is deleted).

**Comment by thedmd** [comment]
Delete operation indeed should remove objects from the lists. Will work on that.
Thanks for reporting.

**Comment by thedmd** [comment]
Objects are now deleted from internal vectors when removed using delete action.
