### ISSUE TITLE
Configurable zoom level?

### ISSUE THREAD

**Issue by Namek** [thedmd/imgui-node-editor#174]
I wish that the zoom level was configurable, in my case I only want to zoom out, which means `zoomLevel >= 1.0f`.

Also, there I think there is a bug. When I zoom in/out in a quick manner, it goes out of range. For example, I very often get the value: 
![obraz](https://user-images.githubusercontent.com/31058/184496236-5a50c7b5-38c9-448e-894c-2753f8b286d2.png)

which is not defined on this list:
```cpp
const float ed::NavigateAction::s_ZoomLevels[] =
{
    0.1f, 0.15f, 0.20f, 0.25f, 0.33f, 0.5f, 0.75f, 1.0f, 1.25f, 1.50f, 2.0f, 2.5f, 3.0f, 4.0f, 5.0f, 6.0f, 7.0f, 8.0f
};
```

And from that value `0.8000...` I can't easily get back to `1.0`. Of course, there are more values not appearing on that list.

**Comment by thedmd** [comment]
You can now define your own zoom levels using `Config::CustomZoomLevels`:

```cpp
        ed::Config config;

        const float zoomLevels[] =
        {
            0.1f, 0.15f, 0.20f, 0.25f, 0.33f, 0.5f, 0.75f, 1.0f,
        };

        for (auto& level : zoomLevels)
            config.CustomZoomLevels.push_back(level);
```

Zoom levels are used to guide zoom-in/zoom-out actions to snap to predefined values.
Actual zoom can be any value, so `0.800000011920929` isn't a bug.
Zooming aim to provide smooth view, it can be interrupted by dragging or other actions which cause it to hold current value.
Please describe me what are you trying to achieve.

As for configurability of zoom levels, I will now close the issue. You can still comment on it.

**Comment by Namek** [comment]
> Zoom levels are used to guide zoom-in/zoom-out actions to snap to predefined values. Actual zoom can be any value, so `0.800000011920929` isn't a bug. Zooming aim to provide smooth view, it can be interrupted by dragging or other actions which cause it to hold current value. Please describe me what are you trying to achieve.

@thedmd 
In my case it's like it doesn't always "snap" to those values. I wish it was impossible for the animation to stop on any value that was not specified in the table.

**Comment by thedmd** [comment]
Can you modify style and set `ScrollDuration` to `0.0f`?
This will bring navigation animation duration to zero making zoom level to snap instantly to target values.

Snapping to preset values and making animation impossible to interrupt is in direct conflict. You can pick one, but not both.

Does this work for you?

**Comment by Namek** [comment]
@thedmd the `ed::GetStyle().ScrollDuration = 0;` doesn't change anything in the behavior for me. The animation is still there and the zoom values still lead to undesired values, not snapping, and I am not aware of any interruption. By any chance, might that be because of a higher DPI (in my case 1.25 scale)?

**Comment by Namek** [comment]
OK, so I checked the behavior with just 2 values and it snaps to either of these values. For me, the problem is rather solved. I understood where the weird value comes from. The returned zoom value is actually inverted scale, that's why it doesn't match the array of default zoom values:

```c++
float ax::NodeEditor::GetCurrentZoom()
{
    return s_Editor->GetView().InvScale;
}
```

However, I believe the 2 bugs still occur:
1. with the default zoom values, it is really hard to get back to scale 1.0f
2. `ScrollDuration` doesn't change anything for me in terms of zooming speed (or I apply it wrong, which is every frame right after `SetCurrentEditor()`)

**Comment by thedmd** [comment]
@Namek
One tick on mouse wheel should snap to next zoom value on the list. Works forward and backward.
If you're overshooting maybe `io.MouseWheel` values are not `1` or `-1` for one tick?
Zooming can perform multiple steps `auto steps    = (int)io.MouseWheel;`
