### ISSUE TITLE
Highlighting links

### ISSUE THREAD

**Issue by SadE54** [thedmd/imgui-node-editor#175]
Hi,

Playing with big schematic , it tends to become unreadable with all the links. Is there a way to highlight all the links connected to a selected node ?

**Comment by thedmd** [comment]
There is not one built in into editor.

You can highlight link by customizing it, `ed::Link` signature accept color and thickness.
```cpp
bool Link(LinkId id, PinId startPinId, PinId endPinId, const ImVec4& color = ImVec4(1, 1, 1, 1), float thickness = 1.0f);
```

Is that enough?

**Comment by SadE54** [comment]
Ok , I will try using already implemented property/methods

**Comment by SadE54** [comment]
Looking at the code I guess I have to go through each link , find the start pin/end pin . And for each look if the node_id is the selected one, and then modify the link color property. Do you see something more efficient without modifying the lib internals ?

**Comment by SadE54** [comment]
Ok, I get it working with : 
`for (auto& link : s_Links)
        {
            auto start_pin = FindPin(link.StartPinID);
            auto end_pin = FindPin(link.EndPinID);
            if (ed::IsNodeSelected(start_pin->Node->ID))
            {
                ed::Link(link.ID, link.StartPinID, link.EndPinID, ImColor(250, 188, 57), 2.0f);
            }
            else if (ed::IsNodeSelected(end_pin->Node->ID))
            {
                ed::Link(link.ID, link.StartPinID, link.EndPinID, ImColor(250, 188, 57), 2.0f);
            }
            else
            {
                ed::Link(link.ID, link.StartPinID, link.EndPinID, link.Color, 2.0f);
            }
        }`

I hope it will be efficient enough. 

Visually , the only drawback is that it changed the color of the link itself. Not like a selected link that keep it's color with a fat orange line below

**Comment by thedmd** [comment]
It really does hijack link color.

I added new color `StyleColor_HighlightLinkBorder` and style flag `HighlightConnectedLinks`. You can trigger this using:
```cpp
ed::PushStyleVar(ed::StyleVar_HighlightConnectedLinks, 1.0f);
for (auto& node : m_Nodes)
{
    // ...
}
ed::PopStyleVar();
```

Flag is captured by node, based on the current value in style while calling `ed::CreateNode`.

![image](https://user-images.githubusercontent.com/1197433/185775279-20380788-d0fd-47ec-a350-75fc5ffa4c9b.png)

**Comment by SadE54** [comment]
Yeah , it's perfect , thanks you  ! 🙏

**Comment by SadE54** [comment]
I tried to change the  color , but it does not seem to work , at least with the provided code  
'''
ed::PushStyleVar(ed::StyleVar_HighlightConnectedLinks, 1.0f);
ed::PushStyleColor(ed::StyleColor_HighlightLinkBorder, ImVec4(0.2, 0.2, 0.20, 1.0));
for (auto& node : s_nodes)
{
...
}
ed::PopStyleColor();
 ed::PopStyleVar();
'''

**Comment by thedmd** [comment]
`HighlightLinkBorder` is applied when drawing links, it is not retained.

Can you try moving it there?
```cpp
ed::PushStyleColor(ed::StyleColor_HighlightLinkBorder, ImVec4(0.2, 0.2, 0.20, 1.0));
for (auto& link : s_Links)
{
    // ...
}
ed::PopStyleColor();
```

**Comment by SadE54** [comment]
I added it here :
```
        ed::PushStyleColor(ed::StyleColor_HighlightLinkBorder, ImVec4(0.1, 0.1, 0.1, 1.0));
        for (auto& link : s_Links)
        {
               ed::Link(link.ID, link.StartPinID, link.EndPinID, link.Color, 2.0f);
        }
        ed::PopStyleColor();
```

It does not seems to work 🤔

**Comment by thedmd** [comment]
Now that you mention it.
I made now link retain highlight color. Should work now.
