### ISSUE TITLE
Fixed width for nodes

### ISSUE THREAD

**Issue by StridingDragon** [thedmd/imgui-node-editor#176]
Currently, every node has an arbitrary size, depending on the fields within it. Is there a way to enforce a fixed width for nodes? For a more organized look, it would really be important to me that the nodes are uniformly the same size.

**Comment by thedmd** [comment]
You can expand every node with minimum size dummy rectangle. If content of the node get bigger, node will still grow.
```cpp
ImGui::Dummy(ImVec2(MIN_NODE_WIDTH, MIN_NODE_HEIGHT));
ImGui::SetCursorScreenPos(ImGui::GetItemRectMin());
```
Is this what are you looking for?

**Comment by StridingDragon** [comment]
Yes, that was it. Thank you so much!
