### ISSUE TITLE
block the save

### ISSUE THREAD

**Issue by Half-People** [thedmd/imgui-node-editor#177]
Hi 
I need make my save to save the blueprint but i don't know how block Save by default

**Comment by thedmd** [comment]
You can hook up save callbacks in Config() structure. Node Editor calls them when it need something to be saved.

**Comment by Half-People** [comment]
> 

I'm a bit stupid, can you be more specific? I still don't understand

**Comment by thedmd** [comment]
NodeEditor `Config` has a place when you can set callback to be called when editor need to save or restore state. There are two sets of callback, one general for whole state, one more specific for saving individual node states. Second set is here in case you will want do keep node state for sake of undo/redo mechanic in your editor.

Please note that blueprints are example of what you can build on top of Node Editor. They're not complete solution, just a mock.
