### ISSUE TITLE
"QueryDeletedNode" clears node settings regardless of calling AcceptDeletedItem/RejectDeletedItem

### ISSUE THREAD

**Issue by MultiPain** [thedmd/imgui-node-editor#178]
If you have an empty loop:
```cpp
NodeEditor::NodeId nodeID;
while (NodeEditor::QueryDeletedNode(&nodeID))
{
}
```
then when you try to delete a node, it will be moved to (0; 0)

similarly if you have something like this:
```cpp
NodeEditor::NodeId nodeID;
while (NodeEditor::QueryDeletedNode(&nodeID))
{
   auto node = getNode(nodeID);
   if (node->isLocked())
   {
      NodeEditor::RejectDeletedItem();
   }
   else
   {
      if (NodeEditor::AcceptDeletedItem()) { /*...*/ }
   }
}
```

The problem is here:
https://github.com/thedmd/imgui-node-editor/blob/459d2d771bf1f5b89e748e91064162e1d52451f2/imgui_node_editor.cpp#L5094-L5096

in ```ed::DeleteItemsAction::RejectItem```:
https://github.com/thedmd/imgui-node-editor/blob/459d2d771bf1f5b89e748e91064162e1d52451f2/imgui_node_editor.cpp#L5072
and
https://github.com/thedmd/imgui-node-editor/blob/459d2d771bf1f5b89e748e91064162e1d52451f2/imgui_node_editor.cpp#L5030

**Comment by thedmd** [comment]
I pushed a fix to this. Can you check if it does work for you?

**Comment by MultiPain** [comment]
@thedmd no, still goes to (0; 0)
I guess 
```Editor->RemoveSettings(item);```
should me moved aswell

**Comment by thedmd** [comment]
@MultiPain I amended last fix, given it wasn't live long.
Deleting should now behave correctly.
Can you double check?

**Comment by MultiPain** [comment]
@thedmd works good

**Comment by thedmd** [comment]
Enjoy : )
