### ISSUE TITLE
Minimizing bp demo window also minimizes comment blocks

### ISSUE THREAD

**Issue by YukinoHayakawa** [thedmd/imgui-node-editor#18]
![image](https://user-images.githubusercontent.com/968003/48050491-fdaf9f00-e1dc-11e8-857d-ecd6d32d687f.png)
minimizes the window and restore
![image](https://user-images.githubusercontent.com/968003/48050506-099b6100-e1dd-11e8-9ac5-95dec1bbe621.png)

**Comment by thedmd** [comment]
Thank you. It is fixed now.
