### ISSUE TITLE
A pin remains filled when the connected node is deleted.

### ISSUE THREAD

**Issue by SC5Shout** [thedmd/imgui-node-editor#182]
- Blueprint example application
![image](https://user-images.githubusercontent.com/43299401/195882458-a50655d8-ce98-497e-9fd1-3f30ad48a5d5.png)

steps to reproduce:
- create 2 nodes
- link pins
- delete one node (don't unlink the pins)

**Comment by thedmd** [comment]
Fixed on `develop`.
