### ISSUE TITLE
How to delete the line linked to self ? 

### ISSUE THREAD

**Issue by ChivenZhang** [thedmd/imgui-node-editor#187]
I have tried the example, and found a shortcoming when linking the input and outout on the same control node. And I cannot delete it as the cursor cannot hover the link line to popup context menu. The image below shows what I have met.
![image](https://user-images.githubusercontent.com/48938612/203746001-40cd7313-20d6-42b2-b4d6-c934fef780b7.png)

The node type below is ok to delete even though It links to self.
![image](https://user-images.githubusercontent.com/48938612/203746359-8ad55e52-48c4-4407-ab7d-b67123d709ab.png)

**Comment by jkooooo99** [comment]
I want to ask the same question!!

**Comment by jkooooo99** [comment]
OK...I just figured it out...use the`.Get()` and turn it to **int** (or whatever your choice).

**Comment by zzc-1024** [comment]
Hold "ALT" can select linking only, then press "Delete" to delete it.

**Comment by thedmd** [comment]
Yes. Holding Alt does cause selection to affect links only.

I have plan to include visual cues to help discover shortcuts present in editor.
