### ISSUE TITLE
error <end Parse>

### ISSUE THREAD

**Issue by satanupup** [thedmd/imgui-node-editor#19]
NodeEditor.h
			template <typename Tag>
			const Tag SafePointerType<Tag>::Invalid{ 0 };

嚴重性	程式碼	說明	專案	檔案	行	隱藏項目狀態
錯誤	C2143	語法錯誤: 遺漏 ';' (在 '<end Parse>' 之前)	NodeEditor	E:\tree\imgui-master\imgui-node-editor-master\NodeEditor\Source\Editor.cpp	5107	

修正為
			template <typename Tag>
			const Tag SafePointerType<Tag>::Invalid( 0 ); // { -> ( , } -> )

**Comment by thedmd** [comment]
Thank you. It is fixed.
