### ISSUE TITLE
Annoucing Dear ImGui Bundle including imgui-node-editor and many others; with support for C++, Python and emscripten

### ISSUE THREAD

**Issue by pthom** [thedmd/imgui-node-editor#196]
I'm happy to announce the first public release of Dear ImGui Bundle. Dear ImGui Bundle is a bundle for Dear ImGui, including many powerful libraries from its ecosystem. It enables to easily create ImGui applications in C++ *and* Python, under Windows, macOS, Linux, emscripten. It is aimed at application developers, researchers, and beginner developers who want to quickly get started.

imgui-node-editor is a central part of it; and it is a joy to use it with the same ease in C++ and python. 

<img width="700" alt="image" src="https://user-images.githubusercontent.com/7694091/214654265-cb88ffcf-365e-49b3-a216-27adafc1cc89.png">

* [Dear ImGui Bundle repo](https://github.com/pthom/imgui_bundle/)
* [Fully interactive online manual](https://traineq.org/ImGuiBundle/emscripten/bin/demo_imgui_bundle.html)
* [Specific annoucement for imgui-node-editor integration](https://github.com/pthom/imgui_bundle/discussions/66)

@thedmd : sorry to hijack the issues list for this, and feel to close this issue; as this is just for your information.  I informed @ocornut [yesterday](https://twitter.com/ocornut/status/1617963615503659008), and I plan to communicate about it in the [ImGui gallery](https://github.com/ocornut/imgui/issues/5886) in the next hours.

**Comment by thedmd** [comment]
Bundle looks awesome, hope newcomers will find it useful. I tooka a look and there is something new for me to discover thanks to your work too.
Thanks for taking time to include node editor too!
Again, awesome! :)

**Comment by pthom** [comment]
Thanks :-)
