### ISSUE TITLE
SaveNodeToMyJsonFile And SaveVariableInNodeOrPin

### ISSUE THREAD

**Issue by Half-People** [thedmd/imgui-node-editor#197]
Hello, I am a developer from Hong Kong, so my English is not very good, I hope you can understand my English

I am now developing an editor to use node editor，I've asked you other questions before，What I want to ask is how to save the original json into my json, because I don't want to save so many things as a project to simply save，This is the first question. In addition, is there a way to save a variable in the node in your node editor? How should I store variables in a node? Because when I used your API before, I created a node class and a pin class, but because getselectnode returns the node id, I used for to find the node class, which is too slow

But this should be my problem that I didn't find

**Comment by thedmd** [comment]
Hello,

Node editor provide callbacks:
https://github.com/thedmd/imgui-node-editor/blob/e78e447900909a051817a760efe13fe83e6e1afc/imgui_node_editor.h#L97-L98

Those are used to serialize state of the editor as a whole. When you need more fine grained control and for example save node state in your own object you can use `SaveNodeSettings` and `LoadNodeSettings` too.
