### ISSUE TITLE
Arch Linux build issue

### ISSUE THREAD

**Issue by OneArb** [thedmd/imgui-node-editor#199]
I am getting the following when building on Arch Linux with running X11 display server protocol

` cmake --build build --config Release`

[  5%] Built target gl3w
[ 22%] Built target imgui
[ 25%] Building CXX object application/CMakeFiles/application.dir/source/renderer_ogl3.cpp.o
/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp: In member function ‘virtual void* RendererOpenGL3::CreateTexture(const void*, int, int)’:
/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp:165:59: error: ‘intptr_t’ in namespace ‘std’ does not name a type
  165 |     return reinterpret_cast<ImTextureID>(static_cast<std::intptr_t>(texture.TextureID));
      |                                                           ^~~~~~~~
/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp: In member function ‘ImVector<ImTexture>::value_type* RendererOpenGL3::FindTexture(ImTextureID)’:
/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp:170:64: error: ‘intptr_t’ in namespace ‘std’ does not name a type
  170 |  auto textureID = static_cast<GLuint>(reinterpret_cast<std::intptr_t>(texture));
      |                                                             ^~~~~~~~

/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp: In lambda function:
/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp:174:37: error: ‘textureID’ is not captured
  174 |         return texture.TextureID == textureID;
      |                                     ^~~~~~~~~
/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp:172:73: note: the lambda has no capture-default
  172 | td::find_if(m_Textures.begin(), m_Textures.end(), [textureID](ImTexture& texture)
      |                                                             ^

/run/media/user/dev/node/imgui-node-editor/examples/application/source/renderer_ogl3.cpp:170:10: note: ‘<typeprefixerror>textureID’ declared here
  170 |     auto textureID = static_cast<GLuint>(reinterpret_cast<std::intptr_t>(texture));
      |          ^~~~~~~~~
make[2]: *** [application/CMakeFiles/application.dir/build.make:146: application/CMakeFiles/application.dir/source/renderer_ogl3.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:262: application/CMakeFiles/application.dir/all] Error 2
make: *** [Makefile:91: all] Error 2

**Comment by niclash** [comment]
This happens on Debian Linux as well.

**Comment by thedmd** [comment]
Fixed now. Thaks for reporting
