### ISSUE TITLE
InputTextMultiline inside a node gets ill-positioned

### ISSUE THREAD

**Issue by francesco-cattoglio** [thedmd/imgui-node-editor#2]
Hi there!
I've been playing alot with your code lately, and I found out that adding a ImGui::InputTextMultiline() inside a Blueprint node is somewhat broken.
If one pans around or zooms, the text area does not move/does not get resized at all.
Not sure if you would be able to figure out what is going on, and if there's an easy fix for that.

**Comment by thedmd** [comment]
I will see what I can do. I suspect that children window is not behaving properly.

**Comment by thedmd** [comment]
Well. I will put a hold on that. InputTextMultiline use child window and it is a bit more complicated to put them in virtual canvas because they have independent state.

**Comment by lmNt** [comment]
I am curious of how you would need to approach this. 
I am very interested in using widgets that use a child window as well, for example `ImGui::Combo`.

Can you maybe roughly outline the steps required? I am interested in approaching this feature, but I am not an expert in imgui and not overly familiar with the node-editor backend yet; so any hint would help me out massively :+1:

**Comment by thedmd** [comment]
I have working example in other project. I will port it here soon.

**Comment by thedmd** [comment]
My bad. I had an example with single line InputText.
After debugging I doubt there is a way to position child window inside canvas. Sorry for making you hope.

On our side we handled an issue by adding '...' button at the end of the line which open an popup with multiline editor.
