### ISSUE TITLE
propose to separate backends and application

### ISSUE THREAD

**Issue by YangShen398** [thedmd/imgui-node-editor#202]
Hi imgui-node-editor developers,

Thanks for making such a great library for drawing node editor in imgui. I really enjoyed it. An issue that I have been experienced so far is to sync the backends with other library which also uses imgui. Now node-editor builds the backends into the Target `application` which does not expose backend headers such that another library cannot use the same backends from imgui-node-editor.

Ideally, I would like to keep all my libraries using the same version of imgui. Since imgui-node-editor has changes in the source code for imgui backends, I would like to let all other libraries use the same backends from imgui-node-editor rather than the original imgui. But now the way that the project is structured makes this impossible. 

I am thinking two different ways to do this.
1. Keep `application` the same. Move all backend headers in the `include` folder and make them public. So when a different library needs to use backends, we just link it against `application`
2. Separate backends and application. Build all backends files into a library called `backends` and link `application` against `backends`. 
We are still use `application` as is now but then we can link other library to the backends from imgui-node-editor.

How do you guys think about this? Or perhaps there is a better way to sync imgui in mulitple libraries? Thoughts?

Thanks,
Yang

**Comment by YangShen398** [comment]
I have created a pull request #203.

**Comment by YangShen398** [comment]
Ok. Now I realized the backends from imgui-node-editor is customized to imgui-node-editor only, not for general use. Having this separation is pointless. Close this issue now.

**Comment by thedmd** [comment]
You're correct. Copy of ImGui is here to power application for examples. CMake project is also there to for examples only.

Intended usage of node editor mimics ImGui approach, where you can simply include all *.cpp and *.h files from root directory and be good to go.

Node editor should compile and work with your own copy of ImGui. If it is not, that is a bug I need to fix.

Thanks for your time.
