### ISSUE TITLE
#define IMGUI_DEFINE_MATH_OPERATORS error 

### ISSUE THREAD

**Issue by arshavirmirzakhani** [thedmd/imgui-node-editor#209]
hi there

when i want to compile the program i will get a imgui_internal.h #define IMGUI_DEFINE_MATH_OPERATORS error
also when i define it i get the same error

also thanks for your awsome project.

**Comment by hugle** [comment]
Hi, you could modify the main header file [imgui_node_editor.h](https://github.com/thedmd/imgui-node-editor/blob/master/imgui_node_editor.h) a bit, by adding the definition before **line 18** will pass the error:

```c++
#define IMGUI_DEFINE_MATH_OPERATORS
#include <imgui.h>
```

Hope that helps.

**Comment by arshavirmirzakhani** [comment]
thanks it helped!

**Comment by thedmd** [comment]
Fix for the issue has been merged to the main branch. Thanks for diagnosing the issue.
