### ISSUE TITLE
Is connect to node self a bug?

### ISSUE THREAD

**Issue by zzc-1024** [thedmd/imgui-node-editor#212]
The Blueprint-example has the code follow:
```C++
bool CanCreateLink(Pin* a, Pin* b)
{
    if (!a || !b || a == b || a->Kind == b->Kind || a->Type != b->Type || a->Node == b->Node)
        return false;
     return true;
}
```

Is the follow code means one pin can't connect to another pin if they are in the same node?
```C++
a->Node == b->Node
```
But it can connect two pins successfully while they are in the same node.
![image](https://user-images.githubusercontent.com/67462033/226184624-190ce16e-2e20-470e-9db3-758d86ebe60c.png)

**Comment by zzc-1024** [comment]
I found that this is not a bug, and the following code is included in the source code:
```C++
else if (endPin->Node == startPin->Node)
{
    showLabel("x Cannot connect to self", ImColor(45, 32, 32, 180));
    ed::RejectNewItem(ImColor(255, 0, 0), 1.0f);
}
```
I just need to uncomment the code.

**Comment by thedmd** [comment]
Blueprints example show what is possible and intended usage of the library. Ultimately power to decide what should be considered a valid connection is on your side.

Good you found your answer.
