### ISSUE TITLE
Question: Is it possible to create function blocks?

### ISSUE THREAD

**Issue by JUNZ1** [thedmd/imgui-node-editor#217]
Hello all, i just found this amazing repo, and thinking to use it for my own project, As a guy who has experience with Unreal Engine, i saw the function blocks and find them really usefull. Question is can i create my own function blocks/node in this project?

**Comment by thedmd** [comment]
Node in node editor is empty rectangular canvas where you can place pins and extra widgets. So generally answer to your question is yes.
Logic behind function blocks however is something that can be built on top of node editor.
