### ISSUE TITLE
Integration to UnrealNetImgui

### ISSUE THREAD

**Issue by sammyfreg** [thedmd/imgui-node-editor#224]
Hi, 

I hope you don't mind, but creating an issue was the easiest way I found to contact the author.

I wanted to let you know that I quickly integrated your library to my [UnrealNetImgui](https://github.com/sammyfreg/UnrealNetImgui) plugin.

This give users easy access to node edition, out of the box. I had looked around a bit, and this library seems the most mature for this feature. I additionally extended your basic interaction sample a little bit, to showcase pin status.

Thank you.

**Comment by thedmd** [comment]
It is odd to see how node editor inspired by Unreal Blueprints made back to Unreal 😄 

Thank you!
