### ISSUE TITLE
Imgui Docking Feature

### ISSUE THREAD

**Issue by Zerocjx** [thedmd/imgui-node-editor#23]
Will there be a new version or branch using `imgui docking` branch? 
I have tried the docking feature of imgui. I like the docking feature and auto layout  very much. It's so convenient.

**Comment by thedmd** [comment]
Nothing in node editor depends on docking. I will update local copy of ImGui to 1.70 latter this day. That should be enough to let you use docking branch without hiccups.

**Comment by thedmd** [comment]
You can find project rebased on docking branch [here](https://github.com/thedmd/imgui-node-editor/tree/docking).

**Comment by Zerocjx** [comment]
Good Job！
