### ISSUE TITLE
ed::Suspend es::Resume break docking branch of ImGui

### ISSUE THREAD

**Issue by gleblebedev** [thedmd/imgui-node-editor#230]
Hey... I'm trying to use the node editor in a game engine. The engine takes imgui from a docking branch.

I need to use the Suspend/Resume for popups but it breaks the editor in a wired ways. For example: https://gyazo.com/3098ab2f4cf8080dc4d48de6e25b28de

I've noticed that the version you have in the repo uses CurrentWindow then LastItemData. Is it something related to my issue? Any ideas how can I fix the editor?

**Comment by TLaviron** [comment]
I'm running into the same issue, when using the latest version for the docking-layout branch here https://github.com/thedmd/imgui/tree/docking-layout which is based on imgui version 1.89.6.
This was running fine with version 1.85 from the (original) docking branch, so I'll try reverting to an earlier version until this is fixed.

**Comment by AdotBdot** [comment]
I have the same issue and don't know how to revert to an earlier version of docking branch.

**Comment by gleblebedev** [comment]
The issue I had was with border evaluation. To fix it I made a workaround that skips one frame before calling NavigateToContent

**Comment by AdotBdot** [comment]
@gleblebedev Could you describe more precisely how to make this workaround?

**Comment by Sage-of-Mirrors** [comment]
#237 This is the same issue I'm having. I don't know how to fix it.

**Comment by Sage-of-Mirrors** [comment]
Seems like a user by the name of glscopeclient found [a workaround](https://github.com/glscopeclient/imgui-node-editor/commit/67e85c2e128ae0a2ef9995948739bb42c640e4e6) for this issue in their fork. The fix works for me, so that's what I'll be using for now.

**Comment by thedmd** [comment]
Fix landed on `develop`. Thanks for your patience.
