### ISSUE TITLE
[Sample] BluePrint Sample  didn't support edit text

### ISSUE THREAD

**Issue by lyd405121** [thedmd/imgui-node-editor#232]
## The problem
- If I add two nodes which are message type with edit controller
- I can't change the content separately as below
![error](https://github.com/thedmd/imgui-node-editor/assets/16344694/4d544cfd-abe2-427a-8dc6-7a4b64e5b61a)

## More try
- I find the other samples have the same problem

**Comment by SC5Shout** [comment]
You probably use the same string buffer with 2 edit texts. Please share your code, so I could be a bit more specific.

**Comment by lyd405121** [comment]
> You probably use the same string buffer with 2 edit texts. Please share your code, so I could be a bit more specific.

## More Info
- I just compile the blueprint-example with latest version
![error](https://github.com/thedmd/imgui-node-editor/assets/16344694/79030be0-4cf5-4d5c-aed6-a2834ba47f65)

## Thanks
- Thanks for your kind advice, I will fix it in my own project

**Comment by IceLuna** [comment]
It's because an example uses the same buffer for all nodes. You should replace it with your own buffer that's unique for each node
![image](https://github.com/thedmd/imgui-node-editor/assets/48557794/3a134b85-25c1-4037-b6ca-149fe723ec7e)

**Comment by lyd405121** [comment]
> It's because an example uses the same buffer for all nodes. You should replace it with your own buffer that's unique for each node ![image](https://private-user-images.githubusercontent.com/48557794/328027017-3a134b85-25c1-4037-b6ca-149fe723ec7e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ5NzQyMzAsIm5iZiI6MTcxNDk3MzkzMCwicGF0aCI6Ii80ODU1Nzc5NC8zMjgwMjcwMTctM2ExMzRiODUtMjVjMS00MDM3LWI2Y2EtMTQ5ZmU3MjNlYzdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA2VDA1Mzg1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3ODQ4OTM5OWYzMGE4MTAyYjc2ODUxOWFkYzY3Y2I2YjhiNTJmNGU1NTIxMzE1ODBjZjAwOTVjYzVjOTYxNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qMxY9HptCYcf7-HyNaEdkXN60BqrzvmmDveD9TiAtWc)

Thanks！
