### ISSUE TITLE
Graphical Bug on Canvas when Hovering Connection over Node Pin

### ISSUE THREAD

**Issue by Sage-of-Mirrors** [thedmd/imgui-node-editor#237]
Hello,

Whenever I hover a node connection over a pin, the node editor canvas glitches out like this:
<img src="https://github.com/thedmd/imgui-node-editor/assets/6289769/f1b4c3fa-9a4e-46b8-9022-4f69ab361148" width="253" height="195" />
When I stop hovering (either by moving the connection off the pin or accepting the new connection), the glitch resolves itself.

I am running the node editor through a docked panel using [hello_imgui](https://github.com/pthom/hello_imgui), which I have modified to use imgui v1.89.3. Has anyone seen this bug before? Are there any suggestions on how to fix it?

Thanks!

**Comment by Sage-of-Mirrors** [comment]
[This workaround](https://github.com/glscopeclient/imgui-node-editor/commit/67e85c2e128ae0a2ef9995948739bb42c640e4e6) by @glscopeclient fixes this bug.

**Comment by thedmd** [comment]
It is fixed now on `develop` and `master`.
