### ISSUE TITLE
ed::Suspend es::Resume trigger canvas exception in a release build, but it's not occur in debug mode~~！

### ISSUE THREAD

**Issue by yangkangnevergiveup** [thedmd/imgui-node-editor#241]
![Snipaste_2023-07-03_20-22-56](https://github.com/thedmd/imgui-node-editor/assets/44560513/dcaf7df8-a519-4b74-8e86-93f8e7142412)

**Comment by thedmd** [comment]
Clipping issue was resolved on `develop` branch. Please check if that solved the issue for you. Thanks!
