### ISSUE TITLE
Build issue(s) - error: ‘ImGuiKey_’ was not declared in this scope

### ISSUE THREAD

**Issue by otto-link** [thedmd/imgui-node-editor#244]
Hi, first thanks for this library!
I'm trying to build it with ImGui master [52125a5](https://github.com/ocornut/imgui/commit/52125a54a57a458e89bc61502010e964add3cdd5) as of today. I came across several known issues: #208, #226, #233.

But now I'm stuck with:
`
external/imgui-node-editor/imgui_node_editor.cpp: At global scope:
external/imgui-node-editor/imgui_node_editor.cpp:48:67: error: ‘ImGuiKey_’ was not declared in this scope; did you mean ‘ImGuiKey_Z’?
   48 |         static int Get(typename std::enable_if<has_nested_ ## Key<ImGuiKey_>::value, T>::type*)     \
      |                                                                   ^~~~~~~~~
external/imgui-node-editor/imgui_node_editor.cpp:60:1: note: in expansion of macro ‘DECLARE_KEY_TESTER’
   60 | DECLARE_KEY_TESTER(ImGuiKey_F);
`

Any idea how I could make this work?

**Comment by thedmd** [comment]
I synchronized `master` with `develop`. There is no point of having the latter in the future as new features will be developed on dedicated branches.

`master` should work well now for you. Please let me know if it does not. Thanks!

**Comment by otto-link** [comment]
Works perfectly, thanks a lot!
