### ISSUE TITLE
Pint out of border of node

### ISSUE THREAD

**Issue by TiberiusFaber** [thedmd/imgui-node-editor#245]
How can I build a node where the pins are out of the boundary of a node? Like in Blender nodes. When I try it, the node rectangle will be increased and resulting the pin inside the node.
![image](https://github.com/thedmd/imgui-node-editor/assets/10845277/e2e5fe5e-a842-4d3c-b4cd-a5a0c1a462b1)

**Comment by thedmd** [comment]
You can explicitly set `ed::PinRect` for pin which can be outside of node boundaries.

Houdini node example does use this to place pins outside node:
https://github.com/thedmd/imgui-node-editor/blob/af7fa51bb9d68c9b44477c341f13a7dadee3e359/examples/blueprints-example/blueprints-example.cpp#L1277
