### ISSUE TITLE
Compile error in 'develop' branch

### ISSUE THREAD

**Issue by niclash** [thedmd/imgui-node-editor#248]
The following compile error occurs in 'develop' branch. Removing `static` takes away the problem.

I am on Debian and gcc-12

```
[ 57%] Building CXX object canvas-example/CMakeFiles/imgui_node_editor.dir/home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_api.cpp.o
In file included from /home/niclas/dev/pony/imgui-node-editor/imgui_extra_math.h:69,
                 from /home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_internal.h:27,
                 from /home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_api.cpp:12:
/home/niclas/dev/pony/imgui-node-editor/imgui_extra_math.inl:37:22: error: ‘ImVec2 operator-(const ImVec2&)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
   37 | inline static ImVec2 operator-(const ImVec2& lhs)
      |                      ^~~~~~~~
/home/niclas/dev/pony/imgui-node-editor/imgui_extra_math.h:36:15: note: previous declaration of ‘ImVec2 operator-(const ImVec2&)’
   36 | inline ImVec2 operator-(const ImVec2& lhs);
      |               ^~~~~~~~
gmake[2]: *** [canvas-example/CMakeFiles/imgui_node_editor.dir/build.make:104: canvas-example/CMakeFiles/imgui_node_editor.dir/home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_api.cpp.o] Error 1
```

**Comment by introverti** [comment]
same error on gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0

**Comment by introverti** [comment]
> The following compile error occurs in 'develop' branch. Removing `static` takes away the problem.
> 
> I am on Debian and gcc-12
> 
> ```
> [ 57%] Building CXX object canvas-example/CMakeFiles/imgui_node_editor.dir/home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_api.cpp.o
> In file included from /home/niclas/dev/pony/imgui-node-editor/imgui_extra_math.h:69,
>                  from /home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_internal.h:27,
>                  from /home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_api.cpp:12:
> /home/niclas/dev/pony/imgui-node-editor/imgui_extra_math.inl:37:22: error: ‘ImVec2 operator-(const ImVec2&)’ was declared ‘extern’ and later ‘static’ [-fpermissive]
>    37 | inline static ImVec2 operator-(const ImVec2& lhs)
>       |                      ^~~~~~~~
> /home/niclas/dev/pony/imgui-node-editor/imgui_extra_math.h:36:15: note: previous declaration of ‘ImVec2 operator-(const ImVec2&)’
>    36 | inline ImVec2 operator-(const ImVec2& lhs);
>       |               ^~~~~~~~
> gmake[2]: *** [canvas-example/CMakeFiles/imgui_node_editor.dir/build.make:104: canvas-example/CMakeFiles/imgui_node_editor.dir/home/niclas/dev/pony/imgui-node-editor/imgui_node_editor_api.cpp.o] Error 1
> ```

Refer to the master branch, just remove the **static** on line 37 of imgui-node-editor/imgui_extra_math.inl
![image](https://github.com/thedmd/imgui-node-editor/assets/73253134/880a1a24-82eb-4efb-be42-90c104e5bd5b)

**Comment by thedmd** [comment]
Resolved on `develop`, thanks!
