### ISSUE TITLE
Customization of imgui causes build error '_FringeScale': is not a member of 'ImDrawList'

### ISSUE THREAD

**Issue by v-strob** [thedmd/imgui-node-editor#25]
I already had an official copy of the imgui library in my program and when I added imgui-node-editor, I get this build error when my codebase references the official imgui.h:
```
'_FringeScale': is not a member of 'ImDrawList'
```
The following commit added _FringeScale to ThirdParty/imgui/imgui.h:
https://github.com/thedmd/imgui-node-editor/commit/11d2dca0c38e1758c551fa0ce4560aea0b799776

However, I don't see any reference to it in the official imgui repo:
https://github.com/ocornut/imgui

This customization to imgui means I have to use your custom version of imgui throughout my codebase.  Even when I built imgui-node-editor, other libraries in my codebase would reference the official imgui.h, which doesn't have `_FringeScale`.  I suggest contributing this change and any other customizations to the imgui project and only consume them once they are merged to master.

If you really want a custom imgui, please rename the source and the public interfaces so that it can coexist with the official imgui library.

**Comment by thedmd** [comment]
I made use of `_FringeScale` optional. What it does it allow anti-aliased geometry look sharp when zoomed in (or out). Extension is available here [feature/draw-list-fringe-scale](https://github.com/thedmd/imgui/tree/feature/draw-list-fringe-scale). I do have plan to propose this as a PR, or at least start discussion about it on official ImGui repo.

I'm aiming to use vanilla copy of ImGui. Last month I made changes that made this goal viable.

Node Editor depends also from [feature/extra-keys](https://github.com/ocornut/imgui/pull/2625), PR is in the queue. Omar is busy at the moment, so there is not way to tell when things will move forward.

At the moment you can comment out this block and move forward. I will investigate how to make this extension optional in the meantime.

https://github.com/thedmd/imgui-node-editor/blob/de9264f6849cd861599ffa404707552b3e02fba4/NodeEditor/Source/imgui_node_editor.cpp#L2794-L2844

**Comment by thedmd** [comment]
I tested changes on vanilla copy of ImGui and node editor compile fine without errors.

You can now use node editor with your local copy of ImGui. :zap:
