### ISSUE TITLE
Please support Imgui 1.89.+

### ISSUE THREAD

**Issue by ChivenZhang** [thedmd/imgui-node-editor#250]
I have updated version of imgui from 1.86 to 1.89, and I saw nothing in my node editor window. So please support newest version of imgui and it's important for the project of my company. Thanks.

Imgui 1.86:
![image](https://github.com/thedmd/imgui-node-editor/assets/48938612/dd360f44-db5d-4d1e-8da0-d6e61120b366)

Imgui 1.89:
![image](https://github.com/thedmd/imgui-node-editor/assets/48938612/8e360253-541d-42a4-aeb3-6c9a7d8b5d3b)

**Comment by ocornut** [comment]
This is discussed in #205

**Comment by thedmd** [comment]
@ChivenZhang Editor should work with latest ImGui properly now. Changes were pushed to `develop` branch.
