### ISSUE TITLE
Calling Suspend may trigger an assert in SentinelDrawCallback()

### ISSUE THREAD

**Issue by pthom** [thedmd/imgui-node-editor#255]
Hi,

I just updated to the latest commit on the develop branch, and I have an issue when calling Suspend and Resume.
Basically, `SentinelDrawCallback` may be called and will trigger an assert. 
This happens when the code inside Suspend/Resume opens an additional window.

I prepared a minimal repro here: 

https://github.com/pthom/node_window_clipping_issue/tree/suspend_resume_issue

(be sure to use the "suspend_resume_issue branch).

I also prepared a quick video explanation here: https://traineq.org/poub/node_editor_issue_suspend.mp4 (1 minute)

Thanks!

**Comment by thedmd** [comment]
@pthom Should be fixed now. Can you confirm it does work for you?

**Comment by pthom** [comment]
Hi Michał,

I confirm the fix works perfectly! Thanks!

**Comment by helynranta** [comment]
Hi @thedmd, would you mind creating a bugfix release for this? Currently the vcpkg port in microsoft/vcpkg repo has the v0.9.2 which is affected by this, it would be great to upgrade it with proper release instead of just commit SHA

**Comment by thedmd** [comment]
@helynranta I did pulish [v0.9.3](https://github.com/thedmd/imgui-node-editor/releases/tag/v0.9.3), hope that helps. Cheers!
