### ISSUE TITLE
Small gap between pin pivot rect and links

### ISSUE THREAD

**Issue by tingyus839** [thedmd/imgui-node-editor#257]
It seems that there is always a small gap between pin pivot rect and the link itself when the width or height of pin pivot rect is greater than zero instead of a point like in Houdini example. Is it possible to remove this gap such that the links touch the border of the pin pivot rect?
![image](https://github.com/thedmd/imgui-node-editor/assets/114398032/87221769-6642-4389-9b5b-26a110b43f81)

**Comment by thedmd** [comment]
Distance is controller by style variable `PinRadius`. Name is unfortunate. I think this is what you're looking for.
`ed::PushStyleVar(ed::StyleVar_PinRadius, 5.0f);`
if you change that to 0.0f, gap will be gone.
