### ISSUE TITLE
Not working correctly in docking branch

### ISSUE THREAD

**Issue by gotocoffee1** [thedmd/imgui-node-editor#26]
For me the nodes appear very small and I can not zoom on them.

**Comment by thedmd** [comment]
I will look into that.
Can you tell on what platform are you using?

**Comment by thedmd** [comment]
Please checkout now.

As a second thought you can use now node editor from master branch with your own copy of ImGui. It will work.

**Comment by gotocoffee1** [comment]
Ah I was a bit confused  cause I  used the imgui docking branch with your master branch (havent seen your docking branch). I tried it now but it still  looks weird. I use the sample code on SDL2 + Opengl3 on Windows. 

![too_small](https://user-images.githubusercontent.com/26260677/60865258-fd611b00-a225-11e9-919f-7088605313a0.png)

**Comment by gotocoffee1** [comment]
I tried the standalone samples and they work fine. It seems that I missunderstood something. I thought the docking branch would also support the viewport feature, which isnt the case, is it?

**Comment by thedmd** [comment]
docking branch use ImGui docking branch, but my imgui_impl_XXX files are from master. If yours have viewport support enabled docking should work.
Let me know if you found the issue.
I may not be able to try SDL2 version today.

**Comment by thedmd** [comment]
I hooked up into SDL2 ImGui example and node editor seems to work fine. Cause is probably somewhere in your code.
![image](https://user-images.githubusercontent.com/1197433/61186442-d6f81100-a665-11e9-9ba1-40daf27eca98.png)

**Comment by gotocoffee1** [comment]
Hi, sorry for the late response. You are right I fucked up some of my settings somehow. Its now working. Thanks

**Comment by thedmd** [comment]
Great you found the issue.
