### ISSUE TITLE
Animate Flow

### ISSUE THREAD

**Issue by lublak** [thedmd/imgui-node-editor#263]
Is would be nice to animate the flow:
a solid line with moving dashes in it as an example.

![grafik](https://github.com/thedmd/imgui-node-editor/assets/44057030/08276466-cb10-4b04-a3cd-69f4846610bb)

**Comment by lublak** [comment]
Alterantive design (moving pearls):
![grafik](https://github.com/thedmd/imgui-node-editor/assets/44057030/4354aa75-cbd0-4039-8245-076638058382)

**Comment by thedmd** [comment]
To animate call 'Flow' function:
https://github.com/thedmd/imgui-node-editor/blob/e78e447900909a051817a760efe13fe83e6e1afc/imgui_node_editor.h#L332

Colors are fully customizable via style.

**Comment by bgribble** [comment]
I have just started using this feature, nice! It would be great if the rendering of the flow marker could be tweaked; I find the default "ball" size to be far too large in my app. Maybe it could be a styleable multiple of the link thickness?
