### ISSUE TITLE
Building errors message on MacOS 

### ISSUE THREAD

**Issue by fatly** [thedmd/imgui-node-editor#264]
ROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to compile fragment shader!
ERROR: 0:8: Invalid call of undeclared identifier 'texture2D'
ERROR: 0:9: Use of undeclared identifier 'col'
ERROR: 0:9: Use of undeclared identifier 'col'
ERROR: 0:9: Use of undeclared identifier 'gl_FragColor'
ERROR: 0:9: Use of undeclared identifier 'col'
ERROR: ImGui_ImplOpenGL3_CreateDeviceObjects: failed to link shader program! (with GLSL '#version 150')
ERROR: One or more attached shaders not successfully compiled

**Comment by igrasping** [comment]
me too  .

**Comment by thedmd** [comment]
Fixed on `develop` and `master`. Thanks for reporting!
