### ISSUE TITLE
No exposed API for detecting dragging of node(s)

### ISSUE THREAD

**Issue by paccerdk** [thedmd/imgui-node-editor#271]
There doesn't seem to be a straightforward method to detect the dragging of nodes. My attempts to find an exposed API for this functionality have been unsuccessful, and I haven't had any success with a proper manual implementation so far.

 **Manual Method Issues**:
   - Attempting a manual method using `ImGui::IsMouseDragging` and `ax::NodeEditor::GetHoveredNode()`, I noticed that `GetHoveredNode()` returns false during dragging. 
   I've checked that its not because `ax::NodeEditor::GetSelectedNodes()` takes over.

   - The `ed::DragAction` seems to provide such functionality, but it is not accessible.

---

#### Additional Observations:

I'm not sure if this is intended or not, and whether its worth filing a separate issue for:

1. **`ax::NodeEditor::HasSelectionChanged()`**:
   - This function appears to always return false, regardless of changes in the selection.

2. **`GetActionContext`**:
   - `ax::NodeEditor::GetActionContextNodes()` appears identical to `ax::NodeEditor::GetSelectedNodes()`.
   - Similarly, `ax::NodeEditor::GetActionContextLinks()` mirrors `ax::NodeEditor::GetSelectedLinks()`.

**Comment by paccerdk** [comment]
Turns out that detecting dragging a node is kind of possible by using:
`ax::NodeEditor::GetHoveredNode()` and `ImGui::IsMouseDragging(ImGuiMouseButton_Left, 1)`
(I wasn't previously setting the second parameter of IsMouseDragging)

I guess i could also detect a group of nodes being dragged in a similar way, by also checking against `nodeEd::GetSelectedNodes()` while dragging.

This might not be an ideal solution, but it works for now.
Leaving the issue open since an exposed API for dragged nodes would still be nice

**Comment by thedmd** [comment]
Well, whole point of node editor was to hide this kind of interaction from user. 😅

Can you tell me what is your use case?

**Comment by paccerdk** [comment]
I need more control for my project, it features network synchronized UI and no-UI editing/processing mode, I'm considering rolling my own based on imgui_canvas.h fork, or switching to Nuklear which seems more suitable for my usage scenario, thanks!

Did you review the Additional Observations?
