### ISSUE TITLE
Question: Embedding editor within a window?

### ISSUE THREAD

**Issue by SheridanR** [thedmd/imgui-node-editor#288]
Hi,

Sorry for the trivial question, but the examples and the documentation (sparse as it is) are not giving me any clues about this.

Whenever I try to embed the editor canvas in a window (ie ImGui::Begin() / ImGui::End()) the canvas is completely broken. Eg:
<img width="1136" alt="Screenshot 2024-04-18 at 12 09 05 " src="https://github.com/thedmd/imgui-node-editor/assets/1526121/120dbb1f-ecb5-451f-962d-2d0931027324">

Here is my code:
```
        if (ImGui::Begin("Node Graph")) {
            ed::SetCurrentEditor(imguiNodeEditorContext);
            ed::Begin("My Editor", ImVec2(1000.f, 750.f));
            int uniqueId = 1;
            // Start drawing nodes.
            ed::BeginNode(uniqueId++);
                ImGui::Text("Node A");
                ed::BeginPin(uniqueId++, ed::PinKind::Input);
                    ImGui::Text("-> In");
                ed::EndPin();
                ImGui::SameLine();
                ed::BeginPin(uniqueId++, ed::PinKind::Output);
                    ImGui::Text("Out ->");
                ed::EndPin();
            ed::EndNode();
            ed::End();
            ed::SetCurrentEditor(nullptr);
        }
        ImGui::End();
```
Changing the size of the canvas eg `ed::Begin("My Editor", ImVec2{0.f, 0.f})` seems to make no difference.

Am I missing something??

**Comment by thedmd** [comment]
I did paste your example into simple-example.cpp and it does look fine.

If this is still issue for you please reopen with more details. Thanks!

![image](https://github.com/thedmd/imgui-node-editor/assets/1197433/60c3548a-b9f6-4131-b4cb-5153d704fd7d)

**Comment by fenix31415** [comment]
Looks like I have similar problem. The canvas doesn't fill available window.
![изображение](https://github.com/user-attachments/assets/1b6479fc-da80-441b-bd50-474416d9d22f)
Moreover, I can move it with scrolling (right button).
![изображение](https://github.com/user-attachments/assets/3ed8aef6-f3eb-446e-8a88-ebdf38f75dd7)
Zoom also have weird behavior: zoom in decreases canvas, while zoom out -- increases.
![изображение](https://github.com/user-attachments/assets/5b03b0da-d499-4f63-8660-727b5d2db824)
![изображение](https://github.com/user-attachments/assets/27ad0727-5e92-40a2-a04c-596f17a228e7)

The code is simple, I even did't create any nodes.

On update:
```cpp
if (ImGui::Begin("Info")) {
	ed::SetCurrentEditor(m_Context);
	ed::Begin("My Editor");
        ed::End();
        ed::SetCurrentEditor(nullptr);
}
ImGui::End();
```

`m_Context` is initialized this way: `m_Context = ed::CreateEditor();` once, while initializing.

**Comment by hitakiri** [comment]
I have same problem. Is there any way to use node-editor in new window?

**Comment by fenix31415** [comment]
I have recently built it by copying code in my project. I.e. without vcpkg. It works fine so far. I haven't enough time to investigate the problem though.

**Comment by MacXxs** [comment]
I'm using imgui v1.90 and NodeEditor v0.9.3, and this issue still persists
![ClippingIssue](https://github.com/user-attachments/assets/81137e21-7d49-4ea8-8281-a8004196b222)
