### ISSUE TITLE
Question about "simple" example

### ISSUE THREAD

**Issue by meshula** [thedmd/imgui-node-editor#29]
In the Simple example, is it expected that one can drag out a connection from on Out pin, and drag it to an In pin? I'm not able to left-drag a connection out of the Out. Before diving too deep into debugging, I thought I should ask this question first :)

**Comment by thedmd** [comment]
Probably simple example is too simple. Currently only setup an editor and draw a single node.
I will add next one with two nodes with ability to make connection. How does that sound? : )

**Comment by meshula** [comment]
Great! I've programmatically created two nodes and a connection between them. Showing how to enable basic interactivity from the UI would be very helpful - there's a big gap between Simple and Blueprint ;)

**Comment by thedmd** [comment]
It is done.

I'm aware API is unique. This is something that was dragged here from prototype and kept for backward compatibility reasons. I think about new simpler one. In the mean time please leave your feedback about it.

**Comment by meshula** [comment]
I'm fine with unique APIs, as long as I can code what I need to code :) That example definitely answers all my initial questions about the expected use pattern, thanks!

**Comment by meshula** [comment]
This new example works great, and I see that the positioning of the wire connecting pins is correct now (previously it was offset away from the pins). Thanks for the example!

**Comment by thedmd** [comment]
I tweaked default to be more sensible. Area where connection can be attached is a rectangle. Now by default it has zero size which make it appear at the center of the pin. Now it is:
![image](https://user-images.githubusercontent.com/1197433/61591473-8a618800-abc7-11e9-80d4-9f64fc7a4a1f.png)
Earlier it was:
![image](https://user-images.githubusercontent.com/1197433/61591478-951c1d00-abc7-11e9-8ace-4a687caeccc0.png)
Using rect allows you to choose where exactly where pivot of the pin will be. There are bunch of function that allows you to position pin pivot in relation to pin itself:
```cpp
void PinPivotRect(const ImVec2& a, const ImVec2& b);
void PinPivotSize(const ImVec2& size);
void PinPivotScale(const ImVec2& scale);
void PinPivotAlignment(const ImVec2& alignment);
```
They are used in blueprints example to make pins in nodes such as:
![image](https://user-images.githubusercontent.com/1197433/61591524-2ee3ca00-abc8-11e9-91b3-12d411e7cdac.png)

Yeah, I need to make docs. : )

**Comment by meshula** [comment]
Ah, that's definitely a valuable feature. Hopefully all the things I get confused about will provide fuel for documentation ;)
