### ISSUE TITLE
Update ImGui to latest version

### ISSUE THREAD

**Issue by thedmd** [thedmd/imgui-node-editor#3]

**Comment by thedmd** [comment]
Update local copy of ImGui to latest version.

References: [ocornut work](https://github.com/ocornut/imgui/pull/846#issuecomment-370437475)

**Comment by Harry09** [comment]
Hi, any updates?

**Comment by thedmd** [comment]
Hello. This is work in progress. But do not hold your breath. I'm dealing with it in my spare time and I don't have much of it lately.

**Comment by thedmd** [comment]
I'm playing around ImGui, so update may be ready soon.

**Comment by arjankuijpers** [comment]
any progress ?

**Comment by thedmd** [comment]
Whole thing took a while, because of [Stack Layout implementation](https://github.com/ocornut/imgui/pull/846) PR had to be ported first.
There are a few bugs to bash left. See #6, where @rhard made an update to 1.61.

**Comment by thedmd** [comment]
I guess we're finally here. Please check out master branch.
