### ISSUE TITLE
Very interested in using this for build a shader editor

### ISSUE THREAD

**Issue by 625673575** [thedmd/imgui-node-editor#33]
Hi ,Im recently working on a shader visual tool.Find your project is very helpful,The liscense is MIT ,so I try to merge this to my exist project ,I noticed the issue with "_FringeScale",but it seems that the ImGui doesn't have some function like ImGui::Spring ImGui::BeginHorizontal.

**Comment by ce2kettu** [comment]
This project uses a slightly modified version of Dear ImGui. What you could do is move these non-standard methods to a new file, but under the ImGui namespace and thus keeping forwards compatibility. Although, you could just replace them with native ImGui methods (BeginGroup, TreeNode).

**Comment by thedmd** [comment]
@625673575, @ce2kettu This project works with vanilla copy of ImGui.

Modifications you mention are required only for blueprints example. Layouts helps to build fancy looking nodes without much hassle.

If you use your own copy of ImGui you will need to draw nodes without layouts with help of BeginGroup as @ce2kettu suggested.
