### ISSUE TITLE
Any way of making Layout Implementation a separate header?

### ISSUE THREAD

**Issue by AleksandarTB** [thedmd/imgui-node-editor#34]
Hello

Is there any way to make your layout feature a separate header from imgui?
For example all your changes to be transferred to a separate header/cpp file named imguiLayout so that we can update imgui easily whenever its needed.

**Comment by thedmd** [comment]
Hello,

I thought about it but layouts need to change some low level functions in order to work. That being said layouts are not required by node editor, they are required only by blueprint example. If you ignore it you should be able to use your own copy of ImGui.
