### ISSUE TITLE
Bug: MoveOverEdge() causes Canvas view to break

### ISSUE THREAD

**Issue by ce2kettu** [thedmd/imgui-node-editor#35]
If you happen to alt+tab or press the windows key while dragging is active, the program will lose focus and `io.MousePos` is set to `ImVec2(-FLT_MAX,-FLT_MAX)`. This does indeed break the scroll calculation [imgui_node_editor.cpp#L3090](https://github.com/thedmd/imgui-node-editor/blob/master/NodeEditor/Source/imgui_node_editor.cpp#L3090).

It can be fixed by checking if mouse position is valid:
``` 
// Mouse is over screen, do nothing
if (screenRect.Contains(screenMousePos) || !ImGui::IsMousePosValid()) return false;
```

**Comment by thedmd** [comment]
Thanks for report. I'm working on fixing that for actions too.

**Comment by thedmd** [comment]
Bug is now fixed on `develop`.
