### ISSUE TITLE
Button on a node opens a popup

### ISSUE THREAD

**Issue by mircolosi** [thedmd/imgui-node-editor#37]
Hi @thedmd ,
I was trying to open a popup on a node via a button. I modified the `Simple.cpp` example with the following function:
```cpp
auto& io = ImGui::GetIO();
const char* button_name = "button";
const char* popup_name = "popup";

ed::SetCurrentEditor(g_Context);
ed::Begin("My Editor", ImVec2(0.0, 0.0f));
int uniqueId = 1;
// Start drawing nodes.
ed::BeginNode(uniqueId++);
  
if (ImGui::Button(button_name)) {
  ImGui::OpenPopup(popup_name);
}
if (ImGui::BeginPopup(popup_name)) {
  ImGui::PushItemWidth(70);
  bool dummy_true = true;
  ImGui::Text("some text");
  ImGui::PopItemWidth();
  ImGui::EndPopup();
}
ed::EndNode();
ed::End();
ed::SetCurrentEditor(nullptr);
```

The problem is that when I scroll the main window, the popup does not update the position, thus it will appear on top of the first position of the button (I hope I was clear).
I think is something related to the `drawList`, but I can't figure how it should work.
Could you give me some hints?
Thank you so much!

**Comment by mircolosi** [comment]
... any news?

**Comment by thedmd** [comment]
I wasn't around to reply earlier, sorry for that.

When you're calling `OpenPopup` please surround it with calls to `ed::Suspend()` and `ed::Resume`. These functions temporary bring back normal ImGui coordinate system, so `OpenPopup` will record correct coordinates for popup to appear.
Please also do same thing with `BeginPopup`/`EndPopup`.

There is how I modified your sample:
```cpp
    ed::SetCurrentEditor(g_Context);
    ed::Begin("My Editor", ImVec2(0.0, 0.0f));
    int uniqueId = 1;
    // Start drawing nodes.
    ed::BeginNode(uniqueId++);

    if (ImGui::Button(button_name)) {
        ed::Suspend();
        ImGui::OpenPopup(popup_name);
        ed::Resume();
    }
    ed::EndNode();

    ed::Suspend();
    if (ImGui::BeginPopup(popup_name)) {
        ImGui::PushItemWidth(70);
        bool dummy_true = true;
        ImGui::Text("some text");
        ImGui::PopItemWidth();
        ImGui::EndPopup();
    }
    ed::Resume();
    ed::End();
```
