### ISSUE TITLE
EditorContext incomplete type error.

### ISSUE THREAD

**Issue by codecnotsupported** [thedmd/imgui-node-editor#38]
I tried to make a "EditorContext" instance with default initialization, which greeted me with a incomplete type error. 

Is this is a bug? Are "CreateEditor", "DestroyEditor" optional or necessary to construct a "EditorContext"?
Why use raw pointers, new, delete to construct/destroy a EditorContext?

Shouldn't the library-user decide whether to store it in a raw pointer?

**Comment by thedmd** [comment]
There is a constructor with default argument that should act like default one.
https://github.com/thedmd/imgui-node-editor/blob/f6678b6701984109257c6f7a8656586794efa512/NodeEditor/Source/imgui_node_editor_internal.h#L1249

Can you check if it work for you if you replace it with:
```cpp
    EditorContext(): EditorContext(nullptr) {}
    EditorContext(const ax::NodeEditor::Config* config);
```

**Comment by codecnotsupported** [comment]
Creating a `ax::NodeEditor::Detail::EditorContext` works fine.
Do it's doesn't work with `ax::NodeEditor::EditorContext`.

I kind of expected a error related to it being a virtual base.

**Comment by thedmd** [comment]
`ax::NodeEditor::EditorContext` is a opaque pointer not related to `ax::NodeEditor::Detail::EditorContext`.
Sorry for making it confusing.
