### ISSUE TITLE
Show custom popup when drawing input pin

### ISSUE THREAD

**Issue by kratochvil-jan** [thedmd/imgui-node-editor#48]
Since drawing combo boxes does not work in the nodes, I am trying to achieve similar behavior with popup boxes. I got the code working, however, there is an ugly graphical glitch that I cannot seem to get rid of.
I am using the blueprints example code. Here is my added code:

`
// defined somewhere at the top
enum class ImageType { Image8U, Image32U };
const ImageType types[] = {ImageType::Image8U, ImageType::Image32U};
const char* items[] = { "Image8U", "Image32U" };

enum class CustomMenuEnum
{
	None = 0,
	ImageType = 1
};

CustomMenuEnum CurrentMenu = CustomMenuEnum::None;

// when drawing the node input pins
for (auto& input : node.Inputs)
{
	auto alpha = ImGui::GetStyle().Alpha;
	if (newLinkPin && !CanCreateLink(newLinkPin, &input) && &input != newLinkPin)
		alpha = alpha * (48.0f / 255.0f);

	builder.Input(input.ID);
	ImGui::PushStyleVar(ImGuiStyleVar_Alpha, alpha);
	DrawPinIcon(input, IsPinLinked(input.ID), (int)(alpha * 255));
	if (!input.Name.empty())
	{
		ImGui::Spring(0);
		ImGui::TextUnformatted(input.Name.c_str());
		ImGui::Spring(0);
	}
	if (input.Type == PinType::ImageType)
	{
		ImageType old = map_pin_image_type[input.ID]; // get current image type associated with the pin
		ImageType now = old;
		const char* current = items[0];
		switch(now)
		{
			case ImageType::Image8U: 	current = items[0]; break;
			case ImageType::Image32U: 	current = items[1]; break;
			default: break;
		}
		if (ImGui::Button(current))
		{
			CurrentMenu = CustomMenuEnum::ImageType;
			ed::Suspend();
			ImGui::OpenPopup("Image Type Menu");
			ed::Resume();
		}

		if (CurrentMenu == CustomMenuEnum::ImageType)
		{
			// show custom menu for image type
			ed::Suspend();
			if (ImGui::BeginPopup("Image Type Menu"))
			{
				for (int i = 0; i < 2; i++)
				{
					if (ImGui::MenuItem(items[i]))
					{
						now = types[i];
						break;
					}
				}

				ImGui::EndPopup();
			}
			else
			{
				CurrentMenu = CustomMenuEnum::None;
			}
			ed::Resume();
		}

		if (old != now)
		{
			// update the image type
			map_pin_image_type[input.ID] = now;
		}
	}
	ImGui::PopStyleVar();
	builder.EndInput();
}
`
Here is how it looks by default:
![Screenshot from 2019-12-25 13-27-28](https://user-images.githubusercontent.com/12199298/71445473-6c6df580-271a-11ea-810c-747fed01ab34.png)
And here how it looks when the popup is shown. You can see the node header text is shifted and so are various UI elements on the top left, as well as the splitter bar.
![Screenshot from 2019-12-25 13-27-54](https://user-images.githubusercontent.com/12199298/71445474-6c6df580-271a-11ea-8789-4eb53df31f74.png)

Any idea what am I doing wrong?

**Comment by thedmd** [comment]
Hello @kratochvil-jan 

Problem is caused by `ed::Suspend()`/`ed::Resume()` called inside node drawing. My recommendation is to deffer any code using them after all nodes and links are done.

To work around that limitation I patched your example:

```cpp
ed::PinId CurrentMenuPinID; // <- PinID for which combo should be open, ed::PinID::Invalid if none
CustomMenuEnum CurrentMenu = CustomMenuEnum::None;
```

In pin drawing:
```cpp
                    if (input.Type == PinType::ImageType)
                    {
                        ImageType old = map_pin_image_type[input.ID]; // get current image type associated with the pin
                        ImageType now = old;
                        const char* current = items[0];
                        switch (now)
                        {
                            case ImageType::Image8U: 	current = items[0]; break;
                            case ImageType::Image32U: 	current = items[1]; break;
                            default: break;
                        }
                        if (ImGui::Button(current))
                        {
                            CurrentMenuPinID = input.ID;
                        }
                    }
```

After drawing:
```cpp
    if (CurrentMenuPinID)
    {
        ed::Suspend();
        if (CurrentMenu == CustomMenuEnum::None)
        {
            ImGui::OpenPopup("Image Type Menu");
            CurrentMenu = CustomMenuEnum::ImageType;
        }

        if (CurrentMenu == CustomMenuEnum::ImageType)
        {
            if (ImGui::BeginPopup("Image Type Menu"))
            {
                for (int i = 0; i < 2; i++)
                {
                    if (ImGui::MenuItem(items[i]))
                    {
                        map_pin_image_type[CurrentMenuPinID] = types[i];
                        CurrentMenu = CustomMenuEnum::None;
                        CurrentMenuPinID = ed::PinId::Invalid;
                    }
                }

                ImGui::EndPopup();
            }
        }
        ed::Resume();
    }
```

And the result is:
![image](https://user-images.githubusercontent.com/1197433/71543000-0a0d3300-296e-11ea-98de-a5031808bca5.png)

**Comment by kratochvil-jan** [comment]
Hi @thedmd, thanks for the tip. Got it up and running already. :]

**Comment by thedmd** [comment]
Great : )

**Comment by prophetl33t** [comment]
Doesn't work properly for me. Popup dissapears instantly.
