### ISSUE TITLE
How to change properly the flow direction?

### ISSUE THREAD

**Issue by chkone** [thedmd/imgui-node-editor#49]
Hello,

What is the clean way to change the flow direction.
For example: Right to Left, Top to Bottom, Bottom to Top
As an illustration:
Houdini:
http://valerioviperino.me/assets/img/articles/kinect-houdini-pcloud/delaunay_pc_graph.png
Unity (with mix of horiontal (Left_Right & Top_Down):
https://forum.unity.com/proxy.php?image=https%3A%2F%2Fi.imgur.com%2FHOq25KV.png%3F1&hash=2def92bc411d60648a04015e2422f29e

Should I override each:
virtual Draw for Node, Link, Pin? (& un-final it)

Thanks

**Comment by thedmd** [comment]
Preferred direction of links between pins can be changed by style.
For example this will make pins accept input from top, and output will be directed down.
```cpp
            ed::PushStyleVar(ed::StyleVar_SourceDirection, ImVec2(0.0f,  1.0f));
            ed::PushStyleVar(ed::StyleVar_TargetDirection, ImVec2(0.0f, -1.0f));
```
You can push/pop style for every other pin. Generally I assign style per node.

Is this what you're looking for?

**Comment by chkone** [comment]
Apparently this change the the first tangents of links.
I'm looking for changing the position of the inputs in the pins.
For example on Houdini Graph. We have the whole readen from top to down. Which implies to have the input pins on the top of end nodes (on the edges). And the output on the bottom on the nodes (in the edges too).
cf. Imgs:
http://valerioviperino.me/assets/img/articles/kinect-houdini-pcloud/delaunay_pc_graph.png
Instead of left to right reading like Blueprint's examples.
Thanks

**Comment by thedmd** [comment]
Pins are rectangles, you can choose choose one that overlap visual part of the pin and one that arrow snap into:
```cpp
ed::PinRect(inputsRect.GetTL(), inputsRect.GetBR());
ed::PinPivotRect(inputsRect.GetTL(), inputsRect.GetBR());
```
They can be placed outside of node rectangle.

![image](https://user-images.githubusercontent.com/1197433/71545848-549fa700-2990-11ea-86a5-056a75c22e25.png)

**Comment by chkone** [comment]
[Fixed]
Thanks
