### ISSUE TITLE
Infinite for loop iterating through m_PreviousPin

### ISSUE THREAD

**Issue by ddengster** [thedmd/imgui-node-editor#53]
Hi, somehow I arrived at an infinite loop regarding iterating through previous_pin pointing to the same node.

![image](https://user-images.githubusercontent.com/3326941/72203891-dfae9000-34ac-11ea-9c1c-62563589474c.png)

![image](https://user-images.githubusercontent.com/3326941/72203913-01a81280-34ad-11ea-8c8e-6fd19629350f.png)

I think the minor problem is that you didn't check if Editor->GetPin(..)  returns the same node as m_LastPin.

In NodeBuilder::BeginPin(..)
Update to 
```
if (m_CurrentPin != m_CurrentNode->m_LastPin)
      m_CurrentPin->m_PreviousPin = m_CurrentNode->m_LastPin;
m_CurrentNode->m_LastPin    = m_CurrentPin;
```

Unfortunately, this leaves me with me being unable to drag my first node around. I'm just using the node editor code from simple.cpp for a few basic nodes encapsulated with a ImGui::Begin()  and ImGui::End(), without your modified imgui. Is there anywhere in the code I can look at to solve this?

**Comment by thedmd** [comment]
Hi.

Do you by any chance have node with two pins with same ID?

**Comment by ddengster** [comment]
> 
> 
> Hi.
> 
> Do you by any chance have node with two pins with same ID?

Ah yes I have. I got it fixed. And the other problem with the first node not moving is that it's NodeId should never be 0.

Thanks!

**Comment by thedmd** [comment]
Zero id is considered invalid or null.

Yes, ids share space (links too). Not sure if that was right decision. Helped a bit with implementation.
Ids are large enough to hold pointers. This is how I use them.

Great you get that working. Cheers!
