### ISSUE TITLE
Vertical flow

### ISSUE THREAD

**Issue by chkone** [thedmd/imgui-node-editor#56]
Hello,

Related to: https://github.com/thedmd/imgui-node-editor/issues/49
Could you share the code (maybe as an example) this code who allows you to display this image?

I tried this:
https://pastebin.com/dmEp0D4u
Testing lot of variation by moving the spring.
Let me know If I did something wrong.

Cheers

**Comment by thedmd** [comment]
Hello,

I added Houdini style notes to demo:
![image](https://user-images.githubusercontent.com/1197433/79262386-84b47c80-7e91-11ea-84d9-aa887aaeeae1.png)

You can inspect code here:
https://github.com/thedmd/imgui-node-editor/blob/4388eca967d4be36c58736b31e7eb1c614f102cc/Examples/Blueprints/Blueprints.cpp#L1199-L1262

**Comment by chkone** [comment]
[Fixed]
Thanks for supporting this project.
