### ISSUE TITLE
Nested State Machine

### ISSUE THREAD

**Issue by bsthorpe** [thedmd/imgui-node-editor#59]
I am trying to create a state machine execution visualization with nested state machines.  I attempted to follow the example of the comment from the blueprints example for grouping the child states of a state machine.  I can add child state machine nodes to the parent node, but  I am having trouble adding pins to the parent node.  After adding a group to the parent node the pins no longer react to links.  

This led to discovering the comment on line 4789 in imgui_node_editor.cpp

https://github.com/thedmd/imgui-node-editor/blob/4388eca967d4be36c58736b31e7eb1c614f102cc/NodeEditor/Source/imgui_node_editor.cpp#L4787-L4796

Is there a reason why groups cannot have pins?

Removing the logic for discarding the pins appears to enable links to be created.  Is there a better approach for creating this type of functionality?

**Comment by thedmd** [comment]
Group nodes act like comment nodes in UE4. They purpose is to enclose some nodes and make them easy to move. They sit in background under nodes and visually group them.

I think what you're expecting them to be is equivalent of macros in UE4 blueprints. Am I right? In that case second instance of node editor in separate ImGui window may be used to edit content of such node.

**Comment by bsthorpe** [comment]
Yes, I think the behavior would be similar to a macro in UE4 blueprints.  Indicating the node is a macro, and allowing another window to open up the editor for the content seems like a workable solution. Thanks.
