### ISSUE TITLE
error Math2D.h

### ISSUE THREAD

**Issue by MGeymer** [thedmd/imgui-node-editor#61]
I found an error during compilation, went to look and there it was.
![Screenshot_4](https://user-images.githubusercontent.com/20752579/79992906-8e5f6500-84cd-11ea-8cbb-63a582627e8b.png)

**Comment by chkone** [comment]
Did you try to compile with "NOMINMAX" on the preprocessor option of the projects.
Or simply add #define NOMINMAX before your first include.

**Comment by thedmd** [comment]
This is a good hunch. Define NOMINMAX before including windows.h and code should compile.
If possible please try to include platform dependent headers in cpp files and as last ones.
windows.h is famous for their defines changing user code in unexpected ways.

**Comment by MGeymer** [comment]
It didn't help, maybe I did something wrong. I am pretty new to C++ and I managed to connect only Simple. Blueprint, I still do not understand how to connect.

**Comment by thedmd** [comment]
Did you try to build samles by following instruction in [readme (click)](https://github.com/thedmd/imgui-node-editor#code) then?

**Comment by thedmd** [comment]
`Math2D.h` is no more after migration to ImGui math routines. Bezier math has been moved and simplified so the issue should be gone.
