### ISSUE TITLE
Possible Improvement ImVec2 additionnal?

### ISSUE THREAD

**Issue by soufianekhiat** [thedmd/imgui-node-editor#64]
Does that make sense to move the Interop operators for ImVec2:
https://github.com/thedmd/imgui-node-editor/blob/master/Examples/Common/BlueprintUtilities/Source/Interop.h#L23
To extra config file with IM_VEC2_CLASS_EXTRA?
https://github.com/ocornut/imgui/blob/f152fac4f1962aedf1d483a5b05a525637354b3a/imgui.h#L215

**Comment by thedmd** [comment]
I don't believe this would be necessary, because in the next update `Interop.h` will be gone. I migrated code to math routines available in ImGui to further simplify code and examples.

Thanks for suggestion.
