### ISSUE TITLE
error in GetBounds function

### ISSUE THREAD

**Issue by wtjcn** [thedmd/imgui-node-editor#65]
in NodeEditor/Source/imgui_node_editor_internal.h file, Line about 1343, GetBounds :

    template <typename T>
    ImRect GetBounds(const std::vector<ObjectWrapper<T>>& objects)
    {
        ImRect bounds;

        for (auto object : objects)
            if (object.m_Object->m_IsLive)
                bounds.Add(object.m_Object->GetBounds());

        return bounds;
    }

It's result always include (0,0) point, the ImRect default init value.
It should "bounds = first GetBounds()" for first Bounds.

**Comment by thedmd** [comment]
Fixed. Thanks for reporting!
