### ISSUE TITLE
在Blueprints例程中有一个bug

### ISSUE THREAD

**Issue by warm-dawn** [thedmd/imgui-node-editor#66]
在例程中, Node保存在s_Nodes当中, s_Nodes是一个std::vector
每一个Node保存有一些Pin
Pin中又有Node*指向它所属于的Node

于是bug出现了, 当s_Nodes增长时 它有可能重新分配空间,从而导致内存地址的更换, 这些Pin所指向的地址将被废弃, 它体内的Node*则成为野指针.

请改为std::list 或map更佳.

**Comment by thedmd** [comment]
To deal with this issue `BuildNodes()` should be called after new node is added, but the call was missing. Fixed.
