### ISSUE TITLE
how i can use begincombo in node 

### ISSUE THREAD

**Issue by CatDroid** [thedmd/imgui-node-editor#67]
when i use ImGui::BeginCombo in node 
the popup list is wrong position, and the size is not corrent

**Comment by chkone** [comment]
Does https://github.com/thedmd/imgui-node-editor/issues/48 helps?

**Comment by CatDroid** [comment]
yeah i see it 
popup should do after all node/pink drawing

**Comment by prophetl33t** [comment]
#48 Doesn't work properly for me. Popup dissapears instantly.

**Comment by thedmd** [comment]
That's true. Widgets which create child windows don't cope well with canvas node editor use.
This is not easy fix atm.

**Comment by AK-test-PK** [comment]
**"Widgets which create child windows don't cope well with canvas node editor use."**

What could be the reason behind this ?
