### ISSUE TITLE
Editor pane reduces height when scrolling on second monitor

### ISSUE THREAD

**Issue by Naios** [thedmd/imgui-node-editor#73]
**imgui-node-editor**: cf3a1c30acc6974ac436fc68859f07a90f4c0add (latest by today)
**imgui** (docking): ocornut/imgui@3d4af15d1d5f5d3746b69859308949c357e0c21e (latest by today)
I'm using the Dear ImGui GLFW & OpenGL Backend on Windows 10

---

First of all, thank you for your awesome library!

I'm encountering an issue together with the ImGui docking branch and imgui-node-editor that if I place the window on my **secondary** monitor the editor pane reduces also its height when scrolling in.
This causes the editor to be much smaller in height, depending on the level of zoom, than actual space available.

I've recorded a small example for better understanding:

![o15W0W2v41](https://user-images.githubusercontent.com/1146834/87848223-53a77600-c8de-11ea-8282-8880a85d8e45.gif)

I'm not sure whether this is caused by imgui-node-editor itself or that I've something missing in my code.
The imgui-node-editor is simply drawn from a dockable window as following:

```cpp
ImGui::Begin("Graph");
ed::Begin("Graph Nodes");
// ...
```

**Comment by thedmd** [comment]
Thanks for report. Node Editor should probably tell ImGui scroll event was consumed. I will look into it.
So far I used editor in the context of whole windows without scrollbar.

**Comment by thedmd** [comment]
It is now fixed on `develop`. Please note that you will have to update to ImGUi 17909 for fix to work (https://github.com/ocornut/imgui/commit/fa963b9aafde7f05b1d32d42e3d2b084c9685e31).
