### ISSUE TITLE
Suggestion: Add VCPKG support.

### ISSUE THREAD

**Issue by nathan130200** [thedmd/imgui-node-editor#74]
Add imgui node editor in vcpkg to support fast and simple building.

**Comment by LouDou** [comment]
Hi,

I've looked into this a bit; I don't think you necessarily have to add anything to this repo to get included in vcpkg.

I've created a fork/branch of vcpkg adding the files required to build this in vcpkg: https://github.com/LouDou/vcpkg/commit/7050ac598dd3a9e9a047fd08b9c842ba37d52074

You can see that it's possible to build this lib in vcpkg using out-of-tree configuration.

It's not the tidiest solution though, I'm no expert on cmake configuration:
- I've set it up to build the 'develop' branch, which is probably not the best idea.
- I've copied a bunch of stuff from your own `misc/cmake-modules/Findimgui_node_editor.cmake` file. 
- It works on my machine. :shrug: 

I guess you'd probably want to put an eye over my commit to see if it makes sense, then we can work towards making a PR against `microsoft/vcpkg` ?

I hope this helps.

Regards,
Doug

**Comment by LouDou** [comment]
Yesterday's commit was missing a couple of things, even though vcpkg built the lib it wasn't usable as dependency.

I've corrected this today: https://github.com/LouDou/vcpkg/tree/imgui-node-editor


Doug.

**Comment by thedmd** [comment]
Thank you @LouDou for your effort!

> I've set it up to build the 'develop' branch, which is probably not the best idea.
`develop` branch is pretty much complete. I need to do some preliminary documentation work and it will be merged to master. My intent is to keep 'develop' operational at all times and have merged there only completed features. Basically to follow git flow. Next release could be switched to 'master' branch.

> I've copied a bunch of stuff from your own misc/cmake-modules/Findimgui_node_editor.cmake file.
All CMake files you find on the repo are harness for examples to be easily built.
Node Editor follow ImGui philosophy were source files are meant do be copied into target project. This is why CMakeLists.txt file is next to examples, not in project root. Reusing `Findimgui_node_editor.cmake` is the right thing to do IMHO.

**Comment by LouDou** [comment]
OK, sounds good. If you can ping me here when you've integrated develop to master then I'll send a PR to microsoft/vcpkg

Regards,
Doug.

**Comment by LouDou** [comment]
I've noticed someone else has now properly added this lib to vcpkg back in september 2023, this issue can be closed I think.

https://github.com/microsoft/vcpkg/pull/33508

**Comment by nathan130200** [comment]
Omg nice ❤
