### ISSUE TITLE
Group bounds not updated when calling `ed::Group(size)`

### ISSUE THREAD

**Issue by Naios** [thedmd/imgui-node-editor#76]
Revision: cf3a1c30acc6974ac436fc68859f07a90f4c0add

When calling successively `ed::Group` with different sizes the size of the group is not updated.

Probably this can be fixed with something like this patch, but it doesn't take manual resizing and regrouping of nodes into account:

```diff
diff --git a/NodeEditor/Source/imgui_node_editor.cpp b/NodeEditor/Source/imgui_node_editor.cpp
index c1911c3..2814fbe 100644
--- a/NodeEditor/Source/imgui_node_editor.cpp
+++ b/NodeEditor/Source/imgui_node_editor.cpp
@@ -4928,7 +4928,13 @@ void ed::NodeBuilder::Group(const ImVec2& size)
     m_IsGroup = true;

     if (IsGroup(m_CurrentNode))
+    {
+        m_CurrentNode->m_GroupBounds.Max = {
+          m_CurrentNode->m_GroupBounds.Min.x + size.x,
+          m_CurrentNode->m_GroupBounds.Min.y + size.y
+        };
         ImGui::Dummy(m_CurrentNode->m_GroupBounds.GetSize());
+    }
     else
         ImGui::Dummy(size);
```

**Comment by thedmd** [comment]
At the moment size is taken into account on first frame to define its initial size.

Proposed change will force group size each frame, which prevent resize using mouse. Please be aware of that.
Groups need better support in API. Separate function to explicitly request group size should do the trick.
Feel free to add one in your copy. I think I will make one on `develop` as soon as I get go groups.

**Comment by thedmd** [comment]
You can find relevant change on `develop` branch. There is new API `SetGroupSize` you can use to change group size.
`Group` function will probably be deprecated in the future.
