### ISSUE TITLE
Avoid capturing imgui widget inputs when node is overlapped.

### ISSUE THREAD

**Issue by AK-test-PK** [thedmd/imgui-node-editor#81]
Hi,
When a node is overlapped onto a ImGui widget, is there a way to prevent the widgets from responding to the click, hover, edit events ?
In the example below, when i overlap the node onto the text box, the text box responds to the input and when overlapped onto the "Hello" button, the button responds to the click.

![test](https://user-images.githubusercontent.com/65729483/93529294-48fa7300-f959-11ea-8dc6-8ce9a74ee216.gif)

**Comment by thedmd** [comment]
Input on nodes is processed in the order of node submission. I think submitting them in the reverse order of drawing may help.

To do that I think you can pull list of ids from `m_Nodes` inside editor which is sorted from bottom to top after ed::End(). And in next frame use these ids to submit nodes in reverse order.

This will require new API function to pull data out.

**Comment by JaroslavHolecek** [comment]
I create little workaround (I draw vector of Nodes m_workspaceCoreNodes in main part and call this after ed::End())
`void WorkspaceWindow::shiftSelectedNodesToFront()
{
    if (ne::HasSelectionChanged())
    {
        std::vector<WorkspaceNodeWithCoreData> selectedCoreNodes = getSelectedWorkspaceCoreNodes();

        for(int i=0; i < selectedCoreNodes.size(); i++)
        {
            coreNodeIter ith_selected_node = std::find_if(m_workspaceCoreNodes.begin(),
                                                        m_workspaceCoreNodes.end(),
                                                        [selectedCoreNodes, i](Ptr<WorkspaceNodeWithCoreData> const &node) -> bool { return node->m_id == selectedCoreNodes.at(i)->m_id; });

            if (ith_selected_node != m_workspaceCoreNodes.end())
            {
              std::iter_swap(m_workspaceCoreNodes.begin()+i, ith_selected_node);
            }
        }
    }
}`

It work well. If I select Node/s. But Node can be in front of other without selecting it (for example after moving).
Can I somehow detect which Node is in front of other? NodeEditor has to know it, because they draw they well.
Something like "lastActiveObjects()"?

**Comment by thedmd** [comment]
Node editor always bring last node user interacted with to the front.

I can add an API that will return node its in order they are arranged in editor, so you can query them after `ed::End()` and rearrange submission order in next frame. Will that be what you need?

**Comment by JaroslavHolecek** [comment]
Yes, If I have order of nodes in node_editor -> I can draw them in same order in next frame and thus reach expected behavior.

**Comment by thedmd** [comment]
OK. I will try to address also this issue this weekend.

**Comment by thedmd** [comment]
Editor can now return order in which nodes are drawn.
![image](https://user-images.githubusercontent.com/1197433/125182944-a88c7c80-e212-11eb-8f0d-436e859b8eb3.png)
