### ISSUE TITLE
ImGui::GetIO().WantCaptureKeyboard always true when editor opened

### ISSUE THREAD

**Issue by Ok23** [thedmd/imgui-node-editor#83]
How prevent dispatch events to my main loop ?

**Comment by thedmd** [comment]
`WantCaptureKeyboard` mean that ImGui want to consume keyboard input and it should not be passed into underlying engine/game/app.

You need to provide more context about the issue. What is happening? What you expected to happen? Any information that you think may help.

**Comment by Ok23** [comment]
```cpp
		ed::SetCurrentEditor(edContext);

		ed::Begin("My Editor");

		int uniqueId = 1;

		// Start drawing nodes.
		ed::BeginNode(uniqueId++);
		ImGui::Text("Node A");
		ed::BeginPin(uniqueId++, ed::PinKind::Input);
		ImGui::Text("-> In");
		ed::EndPin();
		ImGui::SameLine();
		ed::BeginPin(uniqueId++, ed::PinKind::Output);
		ImGui::Text("Out ->");
		ed::EndPin();
		ed::EndNode();

		ed::End();
		if (ImGui::GetIO().WantCaptureKeyboard)
		{
			print("locked");
		}
```
ImGui::GetIO().WantCaptureKeyboard always true even if node editor window not in focus. How to know when block dispatch keyboard input to my main event loop ?

**Comment by thedmd** [comment]
Can you comment out in `imgui_node_editor.cpp` line with `ImGui::CaptureKeyboardFromApp()` and tell if it behave correctly now?

**Comment by thedmd** [comment]
I think call to capture is a leftover. I will remove it since editor does not need text input.

**Comment by SteveWolligandt** [comment]
Hi! Is this actually fixed? I have the same issue and in line 1096 the call to capture is still there. Thanks in advance!

**Comment by thedmd** [comment]
My apologize. I failed to push that change. It is not fixed on `develop`.
