### ISSUE TITLE
Feature Request: Decorator Nodes

### ISSUE THREAD

**Issue by gamagan** [thedmd/imgui-node-editor#85]
Please add the ability to add 'decorator' nodes to sequence nodes. Decorator nodes are useful for creating Behavior Tree editors.
Image example:
https://answers.unrealengine.com/storage/temp/38509-behaviortree.jpg

**Comment by thedmd** [comment]
You can draw them if you need them, exactly like "Sequence". By repeating sequence:
https://github.com/thedmd/imgui-node-editor/blob/687a72f940c76cf5064e13fe55fa0408c18fcbe4/examples/blueprints-example/blueprints-example.cpp#L1119-L1131

**Comment by gamagan** [comment]
Sweet!

**Comment by thedmd** [comment]
I assume you will now what to do next. Good luck!
