### ISSUE TITLE
GroupNode resize instead of move on low zoom

### ISSUE THREAD

**Issue by Vandeer** [thedmd/imgui-node-editor#87]
![image_sample](https://user-images.githubusercontent.com/7627036/95972273-b0f28b00-0e2b-11eb-9dc9-afaec9990df9.gif)

It is very difficult to move it. For wherever you press - resize (although the icon is like for moving).

**Comment by thedmd** [comment]
This will be fixed in next release.

**Comment by thedmd** [comment]
![imgui_group_zones](https://user-images.githubusercontent.com/1197433/101213149-3c450b80-367a-11eb-9d09-9e88d85a18f9.gif)

You can checkout develop branch for the fixed version. I intent to keep it stable.

**Comment by thedmd** [comment]
As mentioned earlier, fix is on develop branch. Will be on master on next release.
