### ISSUE TITLE
dragging viewport with left mouse button

### ISSUE THREAD

**Issue by AartOdding** [thedmd/imgui-node-editor#88]
hey there,

I'm using this library for my project and i really like it! One feature which i would love to have is being able to configure which mouse buttons trigger what interactions, maybe put lasso select on right mouse button and moving the viewport on left, or moving the viewport with the middle mouse button etc. Do you think it would be hard to implement? I'd also be willing to spend some time on this, if you'd be willing to accept any pull requests. What do you think?

**Comment by thedmd** [comment]
Mouse buttons are hardcoded now. Mostly in various actions, but they can be changed to be configurable. It is not hard to do.

**Comment by thedmd** [comment]
It is done, you can now override mouse button indices used in actions via `Config`:
```cpp
            int                     DragButtonIndex;        // Mouse button index drag action will react to (0-left, 1-right, 2-middle)
            int                     SelectButtonIndex;      // Mouse button index select action will react to (0-left, 1-right, 2-middle)
            int                     NavigateButtonIndex;    // Mouse button index navigate action will react to (0-left, 1-right, 2-middle)
            int                     ContextMenuButtonIndex; // Mouse button index context menu action will react to (0-left, 1-right, 2-middle)
```
