### ISSUE TITLE
Missing BeginHorizontal/BeginVertical/EndHorizontal/EndVertical/Spring with vanilla Imgui (1.79) 

### ISSUE THREAD

**Issue by SadE54** [thedmd/imgui-node-editor#94]
Hi, 

It's stated node editor is using vanilla imgui , but if I'm using the last official version of imgui , these functions are missing.
Looking in the node editor source tree, I can found these in imgui.cpp

**Comment by thedmd** [comment]
Node editor does not depend on BeginHorizontal/Vertical, but an example does. 
Can I assume you already figured out that? Assuming you asked for an updated stack layout PR?

**Comment by erwincoumans** [comment]
Ran into the same issue, you can apply this patch: https://github.com/ocornut/imgui/pull/846
