### ISSUE TITLE
[develop][f4317c1] Mouse click-through windows

### ISSUE THREAD

**Issue by ToppDev** [thedmd/imgui-node-editor#99]
Since your develop branch commit f4317c11d40ef988146357d1bad5dc4024613783 your node editor catches all mouse events.
Therefore when you have a window on top, you still perform select actions below.

![Peek 2020-12-28 12-56](https://user-images.githubusercontent.com/17766093/103213313-92217200-490d-11eb-8f0c-60365dd677b5.gif)

**Comment by thedmd** [comment]
Thank you for reporting. It is now fixed.
